
export const COLETANEA_DATA = [
  { number: "1", name: "O SANGUE DE JESUS TEM PODER" },
  { number: "2", name: "O SANGUE DE JESUS TEM PODER PARA SALVAR" },
  { number: "3", name: "CLAMO A TI" },
  { number: "4", name: "QUANDO TE PROSTRARES" },
  { number: "5", name: "CLAMANDO ESTOU" },
  { number: "6", name: "JESUS, Ó MEU JESUS" },
  { number: "7", name: "NESTA HORA EM ORAÇÃO" },
  { number: "8", name: "PELO SANGUE DE JESUS" },
  { number: "9", name: "SENHOR, ME CHEGO A TI" },
  { number: "10", name: "VAMOS LAVAR AS VESTES" },
  { number: "11", name: "REVESTE, SENHOR, TEU POVO" },
  { number: "12", name: "HÁ VITÓRIA PARA MIM" },
  { number: "13", name: "PÕE TEU SANGUE SOBRE MIM" },
  { number: "14", name: "EM TEU ALTAR, SENHOR" },
  { number: "15", name: "CLAMAREI, CLAMAREI" },
  { number: "16", name: "SE ANDARMOS NA LUZ" },
  { number: "17", name: "EM TUA PRESENÇA ENTRAMOS" },
  { number: "18", name: "PROSTRADO ESTOU DIANTE DE TI" },
  { number: "19", name: "TEU POVO CLAMA" },
  { number: "20", name: "O TEU PECADO TU QUERES DEIXAR?" },
  { number: "21", name: "NESTA HORA DE CLAMOR" },
  { number: "22", name: "BENDITO SEJA O CORDEIRO" },
  { number: "23", name: "SENHOR, OUVE A MINHA ORAÇÃO" },
  { number: "24", name: "EIS O CORDEIRO DE DEUS" },
  { number: "25", name: "SENHOR, A TI CLAMO" },
  { number: "26", name: "SEJA SÓ O SENHOR LOUVADO AQUI" },
  { number: "27", name: "CORDEIRO ETERNO" },
  { number: "28", name: "O PODER DO SANGUE DE JESUS" },
  { number: "29", name: "TRANSBORDA-ME, SENHOR" },
  { number: "30", name: "OH! QUE PRECIOSO SANGUE" },
  { number: "31", name: "JUNTO A TI SUPLICO, Ó PAI" },
  { number: "32", name: "O SANGUE DE JESUS, VERTIDO ALI NA CRUZ" },
  { number: "33", name: "EU ME PROSTRO EM TEU ALTAR" },
  { number: "34", name: "QUANDO BUSCAMOS" },
  { number: "35", name: "A MEU SENHOR" },
  { number: "36", name: "CRUCIFICADO FOI MEU JESUS" },
  { number: "37", name: "NESTA HORA ESQUEÇO O MUNDO" },
  { number: "38", name: "PELO SANGUE DE JESUS IREI CLAMAR" },
  { number: "39", name: "JESUS, TU ÉS O MEU DEUS" },
  { number: "40", name: "OH! QUE SANGUE PODEROSO" },
  { number: "41", name: "ALÉM DO VÉU EU QUERO ESTAR" },
  { number: "42", name: "SENHOR, SUPLICO A TI EM ORAÇÃO" },
  { number: "43", name: "VOU CLAMAR" },
  { number: "44", name: "CONFORME A TUA INFINITA GRAÇA" },
  { number: "45", name: "NOS ÁTRIOS DO SENHOR ENTRAMOS" },
  { number: "46", name: "AO SENTIR O TEU PERDÃO" },
  { number: "47", name: "É TEU SANGUE" },
  { number: "48", name: "PELO SANGUE DE JESUS EU VOU CLAMAR" },
  { number: "49", name: "NA HORA EM QUE EU QUISER FALAR COM DEUS" },
  { number: "50", name: "O SANGUE DE JESUS" },
  { number: "51", name: "O CORDEIRO QUE NA CRUZ MORREU" },
  { number: "52", name: "ESCUTA-ME, SENHOR" },
  { number: "53", name: "O SANGUE DO CORDEIRO DE DEUS" },
  { number: "54", name: "HÁ VITÓRIA SEMPRE EM TI, SENHOR" },
  { number: "55", name: "SENHOR, MEU DEUS, MEU PAI" },
  { number: "56", name: "VITÓRIA SOBRE VITÓRIA" },
  { number: "57", name: "EM FERVENTE ORAÇÃO" },
  { number: "58", name: "ATENDE À VOZ DO MEU CLAMOR" },
  { number: "59", name: "SE ORARMOS AO SENHOR" },
  { number: "60", name: "BEM DE MANHÃ, EMBORA O CÉU SERENO" },
  { number: "61", name: "SUBA A MINHA ORAÇÃO" },
  { number: "62", name: "NO SILÊNCIO DA NOITE" },
  { number: "63", name: "INVOCA-ME E TE RESPONDEREI" },
  { number: "64", name: "BRILHE SOBRE MIM" },
  { number: "65", name: "QUANDO O DIA AMANHECE" },
  { number: "66", name: "DE MADRUGADA EU BUSCO A FACE DO SENHOR" },
  { number: "67", name: "TOCA PELA FÉ" },
  { number: "68", name: "LÁ NO CIMO DO MONTE" },
  { number: "69", name: "O ANJO DO SENHOR ESTÁ PASSEANDO" },
  { number: "70", name: "PRECIOSAS SÃO AS HORAS" },
  { number: "71", name: "VEM, AMADO MEU" },
  { number: "72", name: "É PRECISO CONFIAR E BUSCAR A DEUS" },
  { number: "73", name: "DEUS ESTÁ NO TEMPLO" },
  { number: "74", name: "SEI, SENHOR" },
  { number: "75", name: "SENTE EM TUA FACE A GRAÇA" },
  { number: "76", name: "NESTA NOITE FELIZ" },
  { number: "77", name: "VEM, VISITA TUA IGREJA" },
  { number: "78", name: "UMA VOZ MANSA E DELICADA" },
  { number: "79", name: "DEUS ESTÁ PRESENTE ENTRE PECADORES COMO NÓS" },
  { number: "80", name: "VIVES MUITO ALÉM DO CÉU" },
  { number: "81", name: "GRANDE DEUS, ÚNICO DEUS" },
  { number: "82", name: "CADA INSTANTE" },
  { number: "83", name: "MAIS UMA VEZ" },
  { number: "84", name: "ATENDE, SENHOR, A MINHA ORAÇÃO" },
  { number: "85", name: "ENVIA A TUA LUZ" },
  { number: "86", name: "EM TEU NOME" },
  { number: "87", name: "MEU PECADO RESGATADO" },
  { number: "88", name: "DAS PROFUNDEZAS" },
  { number: "89", name: "DAS PROFUNDEZAS CLAMO A TI, Ó SENHOR!" },
  { number: "90", name: "EM TUAS MÃOS, SENHOR" },
  { number: "91", name: "JESUS, A MINH'ALMA TEM SEDE DE TI" },
  { number: "92", name: "PAI CELESTIAL" },
  { number: "93", name: "LOGO DE MANHÃ" },
  { number: "94", name: "BENDITA A HORA DE ORAÇÃO" },
  { number: "95", name: "BUSCAR-ME-EIS" },
  { number: "96", name: "COM A MINHA VOZ CLAMO AO SENHOR (SL. 142)" },
  { number: "97", name: "BUSCOU-ME COM TERNURA" },
  { number: "98", name: "ONDE ESTARIA EU?" },
  { number: "99", name: "UM DIA JESUS ACHOU-ME" },
  { number: "100", name: "EU ME LEMBRO QUANDO JESUS ME TOCOU" },
  { number: "101", name: "QUEM ERA EU ANTES DE CONHECER" },
  { number: "102", name: "MARAVILHOSO E SUBLIME PRA MIM" },
  { number: "103", name: "A MINHA ALMA ESTAVA LONGE DO CAMINHO DO CÉU" },
  { number: "104", name: "VIVI TÃO LONGE DO SENHOR" },
  { number: "105", name: "PERDIDO FOI QUE ELE ME ENCONTROU" },
  { number: "106", name: "PELA FÉ SOMOS SALVOS" },
  { number: "107", name: "QUANDO ANDAVA NO MUNDO ESCRAVIZADO" },
  { number: "108", name: "ISRAEL SAIU DO EGITO" },
  { number: "109", name: "A MINHA VIDA TÃO VAZIA..." },
  { number: "110", name: "OH! QUÃO CEGO ANDEI E PERDIDO VAGUEI" },
  { number: "111", name: "O POVO QUE ANDAVA EM TREVAS" },
  { number: "112", name: "UMA LUZ BRILHOU EM MEU CAMINHO" },
  { number: "113", name: "JESUS, A LUZ DIVINA" },
  { number: "114", name: "AS RIQUEZAS DO MUNDO" },
  { number: "115", name: "GRAÇAS DOU, Ó SENHOR" },
  { number: "116", name: "ACHEI SALVAÇÃO" },
  { number: "117", name: "COMO DESISTIR DESTE GRANDE AMOR?" },
  { number: "118", name: "O SENHOR DEUS DE ISRAEL (EDIFIQUEI UMA CASA)" },
  { number: "119", name: "JESUS, NOME PRECIOSO" },
  { number: "120", name: "JESUS CRISTO MUDOU MEU VIVER" },
  { number: "121", name: "TUDO, Ó CRISTO, A TI ENTREGO" },
  { number: "122", name: "AMO AO SENHOR PORQUE ELE ME OUVIU" },
  { number: "123", name: "SEGUIR-TE-EI" },
  { number: "124", name: "PEREGRINANDO POR SOBRE OS MONTES" },
  { number: "125", name: "PELA FÉ EU CAMINHO" },
  { number: "126", name: "QUERO PROSSEGUIR" },
  { number: "127", name: "ESTOU A CAMINHAR" },
  { number: "128", name: "QUANDO A MÃO DE DEUS EM MIM VEIO TOCAR" },
  { number: "129", name: "FELICIDADE É TER CRISTO AO MEU LADO" },
  { number: "130", name: "TENHO GRANDE GOZO" },
  { number: "131", name: "ÀS VEZES, ALGUÉM ME PERGUNTA" },
  { number: "132", name: "JÁ NÃO ESTOU SOZINHO" },
  { number: "133", name: "EU ESTAVA SÓ, SEM O SENHOR" },
  { number: "134", name: "QUE SEGURANÇA TENHO EM JESUS" },
  { number: "135", name: "EM MEU CORAÇÃO" },
  { number: "136", name: "ESTA PAZ QUE SINTO EM MINH'ALMA" },
  { number: "137", name: "QUE DOCE VOZ TEM MEU SENHOR" },
  { number: "138", name: "HÁ SEMPRE ALGUÉM QUE NÃO PROVOU" },
  { number: "139", name: "NÃO SEI POR QUE DE DEUS O AMOR" },
  { number: "140", name: "AS MUITAS ÁGUAS NÃO PODERIAM APAGAR" },
  { number: "141", name: "O AMOR DE DEUS POR NÓS" },
  { number: "142", name: "CRISTO, MEU MESTRE, SEMPRE HÁ DE AMAR-ME" },
  { number: "143", name: "SE NÃO FOSSE O AMOR" },
  { number: "144", name: "JESUS, AGORA EU BEM SEI" },
  { number: "145", name: "É O AMOR DE DEUS" },
  { number: "146", name: "EXISTE UM ALGUÉM QUE CUIDA DE MIM" },
  { number: "147", name: "CRISTO É TUDO PARA MIM" },
  { number: "148", name: "UMA CERTA VEZ, JESUS CRISTO" },
  { number: "149", name: "JESUS FEZ A PROMESSA" },
  { number: "150", name: "VOU CONTAR-VOS O QUE PENSO DO MEU MESTRE" },
  { number: "151", name: "CRISTO JESUS É O MEU BOM SALVADOR" },
  { number: "152", name: "MAIS PERTO DE JESUS" },
  { number: "153", name: "CRISTO, NOME MAIS ALTO" },
  { number: "154", name: "Ó TU QUE HABITAS ENTRE OS QUERUBINS" },
  { number: "155", name: "HÁ UM SER QUE VIVE EM MIM" },
  { number: "156", name: "TOTALMENTE DESEJÁVEL É O MEU AMADO" },
  { number: "157", name: "CRISTO É A ROSA MAIS BELA" },
  { number: "158", name: "JESUS, O LÍRIO DOS VALES" },
  { number: "159", name: "ELE É A ROSA DE SAROM" },
  { number: "160", name: "EU SOU DO MEU AMADO E ELE ME TEM AFEIÇÃO" },
  { number: "161", name: "ERA UMA OLIVEIRA" },
  { number: "162", name: "GRANDIOSO PARA MIM" },
  { number: "163", name: "TENHO UMA PEDRA VIVA" },
  { number: "164", name: "É BASTANTE PARA MIM A TUA GRAÇA" },
  { number: "165", name: "MARAVILHOSA GRAÇA" },
  { number: "166", name: "O AMADO DE MINH'ALMA" },
  { number: "167", name: "AMO AO MEU SENHOR" },
  { number: "168", name: "TU ÉS FIEL, SENHOR" },
  { number: "169", name: "COMO A FLOR DO CAMPO" },
  { number: "170", name: "EU SOU TÃO FELIZ COM O MEU JESUS" },
  { number: "171", name: "O AMOR DE JESUS É GRANDE" },
  { number: "172", name: "SENHOR, TE AMO, TE AMO" },
  { number: "173", name: "QUANDO JESUS UM DIA" },
  { number: "174", name: "A MINHA HERANÇA É O SENHOR" },
  { number: "175", name: "DESDE O DIA EM QUE TE CONHECI" },
  { number: "176", name: "NÃO EXISTE OUTRO AMOR IGUAL AO TEU, SENHOR" },
  { number: "177", name: "SEMPRE VOU LEMBRAR O QUE FIZESTE POR MIM" },
  { number: "178", name: "O DEUS A QUEM SERVIMOS" },
  { number: "179", name: "PELA FÉ EU POSSO CONTEMPLAR JESUS" },
  { number: "180", name: "ENCONTREI O GRANDE AMOR" },
  { number: "181", name: "EM TI EU ENCONTRO, Ó DEUS, TODA PAZ" },
  { number: "182", name: "COMO É BOM SERVIR AO SENHOR" },
  { number: "183", name: "A MINHA ALEGRIA" },
  { number: "184", name: "REDENTOR ONIPOTENTE" },
  { number: "185", name: "JESUS, SENHOR, ME CHEGO A TI (EU VENHO COMO ESTOU)" },
  { number: "186", name: "PARA QUEM IREMOS NÓS?" },
  { number: "187", name: "MINH'ALMA TEM SEDE DE TI" },
  { number: "188", name: "VENHO, SENHOR, MINHA VIDA OFERECER" },
  { number: "189", name: "DEPENDO DE TI, SENHOR" },
  { number: "190", name: "TODO O MEU SER TE AMA" },
  { number: "191", name: "EU QUERO SENTIR" },
  { number: "192", name: "JESUS, JESUS, EU TE AMO" },
  { number: "193", name: "AS MUITAS ÁGUAS" },
  { number: "194", name: "QUERO ANDAR EM TEU CAMINHO, SENHOR" },
  { number: "195", name: "GRANDE AMOR, Ó GRANDE AMOR" },
  { number: "196", name: "O GRANDE AMOR DO MEU SENHOR" },
  { number: "197", name: "HOJE QUERO SOMENTE AGRADECER" },
  { number: "198", name: "ELE É A MINHA ALEGRIA" },
  { number: "199", name: "COMO É BOM OUVIR TUA VOZ" },
  { number: "200", name: "EU SIRVO UM DEUS" },
  { number: "201", name: "SEU CORPO CANSADO PELAS CAMINHADAS" },
  { number: "202", name: "HÁ UMA FONTE ABERTA NO CALVÁRIO" },
  { number: "203", name: "JESUS IA SUBINDO O MONTE" },
  { number: "204", name: "MORRI NA CRUZ POR TI" },
  { number: "205", name: "JESUS IA SEGUINDO" },
  { number: "206", name: "PAI, A TI ENTREGO O MEU ESPÍRITO" },
  { number: "207", name: "DEUS ENVIOU SEU FILHO AMADO" },
  { number: "208", name: "DEUS AMOU O MUNDO DE TAL MANEIRA" },
  { number: "209", name: "DEUS O SEU FILHO ENVIOU" },
  { number: "210", name: "UM DIA JESUS DESCEU DA SUA GLÓRIA" },
  { number: "211", name: "CORTARAM O MADEIRO" },
  { number: "212", name: "RUDE CRUZ" },
  { number: "213", name: "CRISTO CAMINHAVA EM DIREÇÃO À CRUZ" },
  { number: "214", name: "DOIS DISCÍPULOS NO CAMINHO DE EMAÚS" },
  { number: "215", name: "CERTO HOMEM TÃO NOBRE" },
  { number: "216", name: "SOMOS TEU POVO" },
  { number: "217", name: "DEIXOU O ESPLENDOR DE SUA GLÓRIA" },
  { number: "218", name: "POR AMOR JESUS MORREU" },
  { number: "219", name: "POR AMOR..." },
  { number: "220", name: "NÃO HÁ AMOR IGUAL" },
  { number: "221", name: "JESUS, EM TUA PRESENÇA" },
  { number: "222", name: "EIS QUE ESTOU À PORTA" },
  { number: "223", name: "ONDE ESTÁ O CORDEIRO?" },
  { number: "224", name: "ERA UM PECADOR, ANDAVA SEM JESUS" },
  { number: "525", name: "HÁ UM LINDO PAÍS" },
  { number: "225", name: "JESUS É MELHOR, SIM, QUE OURO E BENS" },
  { number: "226", name: "O SENTIDO DE VIVER" },
  { number: "227", name: "SÓ JESUS TE PODE DAR O QUE PROCURAS" },
  { number: "228", name: "ENTREGA O TEU CAMINHO AO SENHOR" },
  { number: "229", name: "AO POÇO DE JACÓ CHEGOU JESUS" },
  { number: "230", name: "FONTE DE ÁGUAS VIVAS" },
  { number: "231", name: "QUEM ME DÁ ÁGUA" },
  { number: "232", name: "QUEM BEBER DA ÁGUA QUE EU LHE DER" },
  { number: "233", name: "VOU GUIAR-TE A UMA RICA FONTE" },
  { number: "234", name: "DEUS HOJE QUER TE FALAR" },
  { number: "235", name: "MANSO E SUAVE JESUS ESTÁ CHAMANDO" },
  { number: "236", name: "OUVE A VOZ DE JESUS" },
  { number: "237", name: "EIS MENSAGEIROS DO SENHOR" },
  { number: "238", name: "TANTO TEMPO JÁ FAZ QUE O CHAMADO DIVINAL" },
  { number: "239", name: "DEIXA DEUS FALAR AO TEU CORAÇÃO" },
  { number: "240", name: "SE CANSADO TU ESTÁS" },
  { number: "241", name: "MEU AMADO FILHO" },
  { number: "242", name: "SE ESTA NOITE DEUS PEDIR TUA ALMA" },
  { number: "243", name: "JÁ ACHEI UMA FLOR GLORIOSA" },
  { number: "244", name: "EU DESCI PARA O VALE DE BÊNÇÃO E PAZ" },
  { number: "245", name: "POR ONDE QUER QUE EU VÁ" },
  { number: "246", name: "SE EM TEU VIVER" },
  { number: "247", name: "SE ANDA TRISTE É TEU VIVER" },
  { number: "248", name: "SE VOCÊ QUISER SABER" },
  { number: "249", name: "SE EM TUA VIDA FALTA PAZ" },
  { number: "250", name: "SE TU PROCURAS PELA PAZ" },
  { number: "251", name: "A PAZ QUE TU PROCURAS..." },
  { number: "252", name: "SE DISPUSERES O TEU CORAÇÃO - JÓ 11.13-19" },
  { number: "253", name: "SE DISPUSERES O TEU CORAÇÃO" },
  { number: "254", name: "OLHAI PARA O ALTO" },
  { number: "255", name: "MEU CORAÇÃO ENGRANDECE AO SENHOR (CÂNTICO DE VITÓRIA)" },
  { number: "256", name: "NÃO MAIS VIVO EU, MAS CRISTO VIVE EM MIM" },
  { number: "257", name: "TUDO SE FEZ NOVO" },
  { number: "258", name: "SE TU ESTÁS TÃO LONGE DO SENHOR" },
  { number: "259", name: "COM UM BOM PASTOR" },
  { number: "260", name: "DEUS ESTÁ PRESENTE AQUI NESTE LUGAR" },
  { number: "261", name: "CRISTO CAMINHAVA LENTAMENTE" },
  { number: "262", name: "QUERO QUE VOCÊ CONHEÇA" },
  { number: "263", name: "QUERES IR PRA GLÓRIA?" },
  { number: "264", name: "OH! QUE BELOS HINOS HÁ DE LÁ NO CÉU" },
  { number: "265", name: "LEVA TU CONTIGO O NOME" },
  { number: "266", name: "TODOS OS POVOS" },
  { number: "267", name: "QUANDO JESUS SEU SANGUE VERTEU" },
  { number: "268", name: "JESUS É O CORDEIRO" },
  { number: "269", name: "NÃO SEI SE OUVISTE FALAR" },
  { number: "270", name: "SE TU PEDISTE UM SINAL" },
  { number: "271", name: "O CAMINHO QUE NOS LEVA AO CÉU É JESUS" },
  { number: "272", name: "NOVO CAMINHO" },
  { number: "273", name: "O SENHOR É A ALEGRIA" },
  { number: "274", name: "SE EM TUA VIDA NÃO ENCONTRAS PAZ E LUZ" },
  { number: "275", name: "UM MILAGRE É" },
  { number: "276", name: "AINDA QUE OS SEUS SONHOS" },
  { number: "277", name: "ROCHA ETERNA" },
  { number: "278", name: "A NOVA DO EVANGELHO" },
  { number: "279", name: "QUERO ESTAR AO PÉ DA CRUZ" },
  { number: "280", name: "HÁ HOJE ALGUÉM ESPERANDO" },
  { number: "281", name: "ESTE MUNDO NÃO TEM A SUA PAZ" },
  { number: "282", name: "QUEM É QUE DÁ ÁGUA AO SEDENTO?" },
  { number: "283", name: "O MUNDO NÃO SABE..." },
  { number: "284", name: "O AMOR DE DEUS É GRANDE" },
  { number: "285", name: "TU QUE ANDAS SÓ E TRISTE SEM SABER O CAMINHO" },
  { number: "286", name: "UM DIA EU QUIS TE DEIXAR" },
  { number: "287", name: "NÃO TINHA PARECER" },
  { number: "288", name: "BASTA DIZERES O QUE QUERES" },
  { number: "289", name: "ESTENDE TUA MÃO" },
  { number: "290", name: "O QUE OS OLHOS NUNCA VIRAM" },
  { number: "291", name: "SEMPRE QUE QUISERES FALAR CONTIGO" },
  { number: "292", name: "AO SENTIR O MUNDO AO MEU REDOR" },
  { number: "293", name: "ALMA CANSADA" },
  { number: "294", name: "JESUS IA CAMINHANDO (CANTA MEU POVO)" },
  { number: "295", name: "DAS PROFUNDEZAS, A TI CLAMO, Ó SENHOR" },
  { number: "296", name: "TOCA A MINHA DOR, JESUS LEVOU" },
  { number: "297", name: "EM ME VINDO O TEMOR" },
  { number: "298", name: "NEM SEMPRE ENTENDEMOS" },
  { number: "299", name: "HÁ MOMENTOS QUE AS PALAVRAS NÃO RESOLVEM" },
  { number: "300", name: "QUANDO PARECE QUE TUDO ACABOU" },
  { number: "301", name: "QUANDO A TRISTEZA SURGIR" },
  { number: "302", name: "SE A VIDA PARECE PESADA" },
  { number: "303", name: "SE NÃO PUDERES MAIS" },
  { number: "304", name: "BASTA QUE ME TOQUES, SENHOR" },
  { number: "305", name: "O SENHOR É A MINHA LUZ" },
  { number: "306", name: "MEDO TENS? O TENTADOR TE VÁ VENCER?" },
  { number: "307", name: "PELO VALE ESCURO SEGUIREI JESUS" },
  { number: "308", name: "PROFUNDOS VALES EU HEI DE PASSAR" },
  { number: "309", name: "OH! POR QUE DUVIDAR?" },
  { number: "310", name: "MESTRE, O MAR SE REVOLTA" },
  { number: "311", name: "SÓ UMA VOZ ME BASTA" },
  { number: "312", name: "SE, DA VIDA, AS VAGAS PROCELOSAS SÃO" },
  { number: "313", name: "O QUE HABITA NO ABRIGO DE DEUS..." },
  { number: "314", name: "QUE IMPORTA" },
  { number: "315", name: "SE EM PROFUNDO ABISMO TE ENCONTRAS" },
  { number: "316", name: "A VIDA NO MUNDO É CRUEL" },
  { number: "317", name: "QUANDO VEM NOS OLHOS UMA LÁGRIMA" },
  { number: "318", name: "QUANDO A ANGÚSTIA VEM" },
  { number: "319", name: "MAIS PERTO QUERO ESTAR" },
  { number: "320", name: "BOM É O SENHOR" },
  { number: "321", name: "QUÃO BONDOSO AMIGO É CRISTO" },
  { number: "322", name: "HÁ UM AMIGO SEMPRE JUNTO" },
  { number: "323", name: "DEUS ESTÁ PRESENTE SEMPRE PRONTO A NOS AJUDAR" },
  { number: "324", name: "EU SOU POBRE E NECESSITADO" },
  { number: "325", name: "SE HOJE ESCUTARES" },
  { number: "326", name: "EU NÃO SABERIA CAMINHAR" },
  { number: "327", name: "DEUS É CONTIGO" },
  { number: "328", name: "CONSOLAI, CONSOLAI O MEU POVO" },
  { number: "329", name: "ATUA EM NOSSO MEIO" },
  { number: "330", name: "EIS AÍ O DIA ACEITÁVEL" },
  { number: "331", name: "SE DEUS É POR NÓS" },
  { number: "332", name: "O REI E EU" },
  { number: "333", name: "SE TE ENCONTRARES TRISTE" },
  { number: "334", name: "DEUS CUIDA DE TI" },
  { number: "335", name: "NÃO DESANIMES! DEUS PROVERÁ" },
  { number: "336", name: "HÁ ALGUÉM QUE CUIDA DE TI" },
  { number: "337", name: "O MESMO DEUS" },
  { number: "338", name: "DIVINO COMPANHEIRO" },
  { number: "339", name: "PARA OS MONTES OLHAREI" },
  { number: "340", name: "DEUS TE GUARDARÁ" },
  { number: "341", name: "QUE CONSOLAÇÃO" },
  { number: "342", name: "ROCHA MINHA" },
  { number: "343", name: "OS QUE CONFIAM NO SENHOR" },
  { number: "344", name: "CONFIO EM DEUS" },
  { number: "345", name: "EM NADA PONHO A MINHA FÉ" },
  { number: "346", name: "SE A FÉ POR VEZES FALTA" },
  { number: "347", name: "FIRME NAS PROMESSAS" },
  { number: "348", name: "ESPERA NO SENHOR, ANIMA-TE" },
  { number: "349", name: "SE NÃO FOSSE O SENHOR" },
  { number: "350", name: "FAZE-ME INABALÁVEL" },
  { number: "351", name: "TU ÉS MEU REI" },
  { number: "352", name: "QUERES NESTE MUNDO SER UM VENCEDOR?" },
  { number: "353", name: "DEIXA-ME CHORAR" },
  { number: "354", name: "CRISTO ME DARÁ" },
  { number: "355", name: "VENCER, VENCER" },
  { number: "356", name: "O SENHOR É O MEU PASTOR (REFRIGERA A MINHA ALMA)" },
  { number: "357", name: "O SENHOR É O MEU PASTOR (BONDADE E MISERICÓRDIA)" },
  { number: "358", name: "O SENHOR É O MEU PASTOR (SL 23)" },
  { number: "359", name: "DEUS É NOSSO AMPARO, NOSSA FORTALEZA" },
  { number: "360", name: "ROCHEDO FORTE É O SENHOR" },
  { number: "361", name: "NÃO HÁ DEUS ACIMA DO SENHOR" },
  { number: "362", name: "DEUS PROVERÁ" },
  { number: "363", name: "QUANDO AS LUTAS ME CERCAM" },
  { number: "364", name: "DÁ-ME MAIS FÉ" },
  { number: "365", name: "NÃO TEMAS, POIS TE ESCOLHI (QUANDO PELAS ÁGUAS)" },
  { number: "366", name: "AS LÁGRIMAS FALAM, JESUS TE ESCUTA" },
  { number: "367", name: "SE AS LUTAS DA VIDA" },
  { number: "368", name: "ESFORÇA-TE, TEM BOM ÂNIMO!" },
  { number: "369", name: "QUANDO MAIS NINGUÉM TE COMPREENDE" },
  { number: "370", name: "JESUS É A ROCHA INABALÁVEL" },
  { number: "371", name: "TODA PROMESSA" },
  { number: "372", name: "MUITOS SÃO OS QUE CONFIAM" },
  { number: "373", name: "SE UM DIA DEUS PROMETEU" },
  { number: "374", name: "QUERO TOCAR EM TUAS VESTES, SENHOR" },
  { number: "375", name: "OS SEGREDOS DO TEU CORAÇÃO" },
  { number: "376", name: "O SENHOR TE GUIARÁ" },
  { number: "377", name: "DEUS É MINHA ROCHA" },
  { number: "378", name: "CONFIA E ORA" },
  { number: "379", name: "ALGEMADO POR UM PESO" },
  { number: "380", name: "POSSO SENTIR O SEU TOQUE EM MIM (GLORIFICA)" },
  { number: "381", name: "MEU DEUS VENCE BATALHAS" },
  { number: "382", name: "JÁ CHEGUEI ATÉ AQUI (VITÓRIAS)" },
  { number: "383", name: "LÁ ONDE EU NÃO POSSO VER (A ORAÇÃO)" },
  { number: "384", name: "BEM SEI QUE TUDO PODES" },
  { number: "385", name: "QUÃO DIFÍCIL É, SENHOR (FAZE-ME UM VENCEDOR)" },
  { number: "386", name: "QUAL O ADORNO DESTA VIDA?" },
  { number: "387", name: "SONDA-ME, Ó DEUS" },
  { number: "388", name: "SÓ TU ÉS, SENHOR" },
  { number: "389", name: "SENHOR, O QUE É A NOSSA VIDA?" },
  { number: "390", name: "CANTAREI A MISERICÓRDIA" },
  { number: "391", name: "CANTAREI A BONDADE E A JUSTIÇA" },
  { number: "392", name: "EU SÓ QUERO SER, SENHOR" },
  { number: "393", name: "QUERO SER FIEL AO MEU SENHOR" },
  { number: "394", name: "UMA VOZ ME DISSE LÁ DO CÉU" },
  { number: "395", name: "FALA, JESUS QUERIDO" },
  { number: "396", name: "ABBA PAI" },
  { number: "397", name: "HÁ UMA LUZ A BRILHAR" },
  { number: "398", name: "ENTREI NO TEMPO DE DEUS" },
  { number: "399", name: "QUAL MADEIRA" },
  { number: "400", name: "EU QUERO SER, SENHOR AMADO" },
  { number: "401", name: "COMO TU QUERES" },
  { number: "402", name: "A LEI DO SENHOR É PERFEITA" },
  { number: "403", name: "AQUELE QUE TEM OS MEUS MANDAMENTOS" },
  { number: "404", name: "JESUS, QUERO AMAR-TE" },
  { number: "405", name: "AMO AO SENHOR DE TODO O MEU CORAÇÃO" },
  { number: "406", name: "JESUS, OH, NÃO EU MAIS QUERO NO MUNDO" },
  { number: "407", name: "EU VI O SENHOR" },
  { number: "408", name: "EIS QUE SURGE UM POVO FORTE" },
  { number: "409", name: "EIS MARCHAMOS PARA AQUELE BOM PAÍS" },
  { number: "410", name: "UM PENDÃO REAL VOS ENTREGOU O REI" },
  { number: "411", name: "O SENHOR DA CEIFA ESTÁ CHAMANDO" },
  { number: "412", name: "SOU FORASTEIRO AQUI" },
  { number: "413", name: "OUVI, Ó CÉUS, E FALAREI" },
  { number: "414", name: "MEU DEUS, MEU BOM PASTOR" },
  { number: "415", name: "QUERO SER UM VASO DE BENÇÃO" },
  { number: "416", name: "PELAS PRAIAS GALILEIAS EM JESUS" },
  { number: "417", name: "MINHA DEDICAÇÃO" },
  { number: "418", name: "HÁ UM POVO QUE TE ADORA" },
  { number: "419", name: "HÁ UMA OBRA QUE DEUS QUER FAZER" },
  { number: "420", name: "SOMOS TEU POVO E QUEREMOS" },
  { number: "421", name: "A OBRA DO SENHOR É PERFEITA" },
  { number: "422", name: "A MINHA HERANÇA..." },
  { number: "423", name: "Ó PASTOR DE ISRAEL" },
  { number: "424", name: "O MEU AMADO DESCEU AO SEU JARDIM" },
  { number: "425", name: "QUE VISTA AMÁVEL É" },
  { number: "426", name: "UM CORPO SÓ, UM SÓ ESPÍRITO" },
  { number: "427", name: "OH! QUÃO BOM E QUÃO SUAVE É" },
  { number: "428", name: "VEM, Ó CRISTO, ENCHER MEU CÁLICE" },
  { number: "429", name: "ÉS O PÃO DA VIDA" },
  { number: "430", name: "COMO CRISTO ENSINOU" },
  { number: "431", name: "CRISTO JÁ NOS PREPAROU" },
  { number: "432", name: "OUÇO A VOZ DO MEU AMADO ME CHAMAR" },
  { number: "433", name: "TOMAI AGORA O PÃO" },
  { number: "434", name: "HÁ UM DOCE ESPÍRITO AQUI" },
  { number: "435", name: "FLUIRÁ COMO UM RIO" },
  { number: "436", name: "ESPÍRITO DO TRINO DEUS" },
  { number: "437", name: "VEM SOBRE MIM, ESPÍRITO DE DEUS" },
  { number: "438", name: "O ESPÍRITO DO SENHOR ESTÁ SENDO DERRAMADO" },
  { number: "439", name: "Ó VEM DERRAMAR" },
  { number: "440", name: "DERRAMAREI MEU ESPÍRITO" },
  { number: "441", name: "ESPÍRITO SANTO, Ó CONSOLADOR" },
  { number: "442", name: "MAIS DO TEU SANTO ESPÍRITO" },
  { number: "443", name: "HÁ UM RIO DE ÁGUAS VIVAS" },
  { number: "444", name: "DESEJEI ARDENTEMENTE" },
  { number: "445", name: "DIRIGE-ME, SENHOR" },
  { number: "446", name: "A TUA PALAVRA..." },
  { number: "447", name: "SENHOR, GUIA-NOS" },
  { number: "448", name: "SENHOR, EU QUERO SERVIR-TE" },
  { number: "449", name: "A MINHA VIDA ENTREGO" },
  { number: "450", name: "A TUA JUSTIÇA" },
  { number: "451", name: "NO SERVIÇO DO MEU REI EU SOU FELIZ" },
  { number: "452", name: "QUERO QUE ME TOQUES, SENHOR" },
  { number: "453", name: "QUANDO DOBRO OS MEUS JOELHOS EM ORAÇÃO" },
  { number: "454", name: "SENHOR, MEU DEUS, O QUE DIREI DE TI? (SAÚDE ESPIRITUAL)" },
  { number: "455", name: "QUANTO MAIS EU TE CONHEÇO (CAMINHO FELIZ)" },
  { number: "456", name: "CHUVAS DE BÊNÇÃOS TEREMOS" },
  { number: "457", name: "INSTRUMENTO EM TUAS MÃOS" },
  { number: "458", name: "Ó CRISTO! PÃO DA VIDA" },
  { number: "459", name: "É TEMPO, É TEMPO" },
  { number: "460", name: "Ó JESUS! Ó VERA PÁSCOA" },
  { number: "461", name: "TU, Ó SENHOR, TU ÉS TÃO PURO DE OLHOS (AVIVA A TUA OBRA)" },
  { number: "462", name: "QUANTOS FIÉIS, SENHOR" },
  { number: "463", name: "VEM, SENHOR, VISITA TUA VINHA" },
  { number: "464", name: "TU QUE SOBRE A AMARGA CRUZ" },
  { number: "465", name: "O ESTANDARTE DESTA IGREJA" },
  { number: "466", name: "EIS O ESTANDARTE" },
  { number: "467", name: "OS GUERREIROS SE PREPARAM" },
  { number: "468", name: "HÁ TANTA TERRA" },
  { number: "469", name: "CASTELO FORTE" },
  { number: "470", name: "NO GETSÊMANI" },
  { number: "471", name: "VEM, ESPÍRITO DE DEUS" },
  { number: "472", name: "VINDE, CANTAI E ENTOAI LOUVORES A JESUS" },
  { number: "473", name: "MINHA ORAÇÃO" },
  { number: "474", name: "QUEM SOU EU, SENHOR?" },
  { number: "475", name: "AINDA UMA VEZ (AGEU)" },
  { number: "476", name: "ESTA OBRA É DE DEUS" },
  { number: "477", name: "SEMPRE VOU LEMBRAR" },
  { number: "478", name: "VI UM NOVO CÉU" },
  { number: "479", name: "QUEM ME DERA" },
  { number: "480", name: "EU ESPERO, ANSIOSO, POR MEU DEUS" },
  { number: "481", name: "ASSIM COMO A NOITE ESPERA PELO DIA" },
  { number: "482", name: "OS SINAIS DO FIM SE CUMPEM" },
  { number: "483", name: "CHEGOU O TEMPO DE PENSAR" },
  { number: "484", name: "TEMEI A DEUS" },
  { number: "485", name: "SETE CASTIÇAIS" },
  { number: "486", name: "DO NORTE VEM O ÁUREO ESPLENDOR" },
  { number: "487", name: "VIGIAI E SEMPRE ORAI, Ó CRENTES" },
  { number: "488", name: "CERTO VEZ, AO ORAR" },
  { number: "489", name: "EM BREVE ESCUTAREI" },
  { number: "490", name: "ELE VOLTARÁ PRA BUSCAR A SUA IGREJA" },
  { number: "491", name: "ELE UM DIA VOLTARÁ" },
  { number: "492", name: "ELE VOLTARÁ, SIM, ELE VOLTARÁ" },
  { number: "493", name: "COMO FOI PARA O CÉU, JESUS CRISTO HÁ DE VIR" },
  { number: "494", name: "NÃO SEI QUANDO CRISTO JESUS HÁ DE VIR" },
  { number: "495", name: "O QUE HÁ DE VIR, VIRÁ" },
  { number: "496", name: "NÃO VAI TARDAR" },
  { number: "497", name: "JESUS, SIM, VEM, DO CÉU EM GLÓRIA ELE VEM" },
  { number: "498", name: "CRISTO VEM ME BUSCAR" },
  { number: "499", name: "OUÇO UMA VOZ TÃO SUAVE" },
  { number: "500", name: "SEI QUE O SENHOR" },
  { number: "501", name: "O ESPÍRITO DE DEUS FALA À SUA IGREJA" },
  { number: "502", name: "QUANDO LÁ DO CÉU DESCENDO" },
  { number: "503", name: "TENHO SAUDADES DE JESUS, MEU MESTRE" },
  { number: "504", name: "EU SEI QUE JESUS" },
  { number: "505", name: "OS SEUS CABELOS BRANCOS" },
  { number: "506", name: "TU QUE ESTÁS ASSENTADO" },
  { number: "507", name: "O SOL ESCURECERÁ" },
  { number: "508", name: "BREVE MEU CÉU JESUS HÁ DE APARECER" },
  { number: "509", name: "EM BREVE, MUI BREVE" },
  { number: "510", name: "ALERTA POVO, ESTÁ CHEGANDO A NOSSA HORA" },
  { number: "511", name: "JESUS CRISTO VOLTARÁ COM SEU GRANDE ESPLENDOR" },
  { number: "512", name: "O MEU AMADO FALA E ME DIZ" },
  { number: "513", name: "QUEM É ESTA QUE APARECE" },
  { number: "514", name: "ESTA É A VOZ, A VOZ DO MEU AMADO" },
  { number: "515", name: "QUANDO A ÚLTIMA TROMBETA ECOAR" },
  { number: "516", name: "QUANDO A ANGELICAL TROMBETA" },
  { number: "517", name: "JÁ NÃO TARDA O AMANHECER" },
  { number: "518", name: "NÃO TEREI MAIS TRISTEZAS" },
  { number: "519", name: "UM NOVO LAR ME ESPERA" },
  { number: "520", name: "NO TRONO DA CIDADE DE DEUS" },
  { number: "521", name: "AO CHEGAR AO CÉU GOZO EU TEREI" },
  { number: "522", name: "EXISTE UM LAR" },
  { number: "523", name: "LÁ NO CÉU, AMIGOS CANTAM" },
  { number: "524", name: "SE EU ESTIVESSE NA ALVORADA" },
  { number: "526", name: "LINDO! LINDO! LINDO!" },
  { number: "527", name: "REGOZIJAI-VOS" },
  { number: "528", name: "EU AVISTO UMA TERRA FELIZ" },
  { number: "529", name: "EU OUVI DA FORMOSA CIDADE" },
  { number: "530", name: "OH! QUE SAUDOSA LEMBRANÇA" },
  { number: "531", name: "JERUSALÉM, JERUSALÉM" },
  { number: "532", name: "QUANDO O MUNDO AQUI DEIXAR" },
  { number: "533", name: "MINHA ALMA, POIS, ALEGRE CANTA" },
  { number: "534", name: "BREVE VOLTARÁ O MESSIAS" },
  { number: "535", name: "ALÉM DO CÉU AZUL" },
  { number: "536", name: "FINDA A LIDA TERREAL" },
  { number: "537", name: "QUANDO O JORDÃO PASSARMOS UNIDOS" },
  { number: "538", name: "HÁ UM LUGAR PRA MIM" },
  { number: "539", name: "JUNTO AO TRONO DE DEUS, PREPARADO" },
  { number: "540", name: "OH! PENSAI NESSE LAR LÁ DO CÉU" },
  { number: "541", name: "ARREBATADO FUI NO DIA DO SENHOR" },
  { number: "542", name: "AO LADO DE JESUS EU QUERO ESTAR" },
  { number: "543", name: "AO LADO DE DEUS" },
  { number: "544", name: "EM BREVE O DIA CHEGARÁ" },
  { number: "545", name: "JESUS ESTÁ ÀS PORTAS" },
  { number: "546", name: "OH! QUANTO ALMEJO ESTAR" },
  { number: "547", name: "Ó VEM LOGO, JESUS" },
  { number: "548", name: "NAS LINDAS MORADAS" },
  { number: "549", name: "MARAVILHOSO SERÁ" },
  { number: "550", name: "CANTAI, Ó IGREJA" },
  { number: "551", name: "TENHO LIDO DA BELA CIDADE (A BELA CIDADE)" },
  { number: "552", name: "PÁTRIA MINHA" },
  { number: "553", name: "VEM! MARANATA, JESUS VEM!" },
  { number: "554", name: "JERUSALÉM (SUAS RUAS DE OURO)" },
  { number: "555", name: "DA LINDA PÁTRIA" },
  { number: "556", name: "NA NOVA JERUSALÉM IREI MORAR" },
  { number: "557", name: "ESTE MUNDO JAMAIS PODE ME SEPARAR" },
  { number: "558", name: "VEM, JESUS CRISTO, JÁ VEM" },
  { number: "559", name: "A ÚLTIMA TROMBETA SOARÁ..." },
  { number: "560", name: "EIS QUE ESTOU À PORTA E BATO" },
  { number: "561", name: "OUVI COMO QUE A VOZ DE UMA GRANDE MULTIDÃO" },
  { number: "562", name: "QUANDO MEU TEMPO DE LUTAS PASSAR" },
  { number: "563", name: "NÃO SE TURBEM OS VOSSOS CORAÇÕES" },
  { number: "564", name: "DISPÕE-TE, RESPLANDECE" },
  { number: "565", name: "LÁ ESTÁ O MEU TESOURO" },
  { number: "566", name: "O SENHOR É O MEU PASTOR (MARANATA, JESUS VEM)" },
  { number: "567", name: "QUANDO SERÁ O GRANDE DIA" },
  { number: "568", name: "SENHOR, QUANDO NAS ÁGUAS" },
  { number: "569", name: "JESUS VEM! VEM NOS BUSCAR!" },
  { number: "570", name: "JÁ REFULGE A GLÓRIA ETERNA (VENCENDO VEM JESUS!)" },
  { number: "571", name: "O GRANDE DIA ESTÁ CHEGANDO" },
  { number: "572", name: "CHEGUEMOS AO ALTAR DE JESUS" },
  { number: "573", name: "COMO É BOM TE ADORAR" },
  { number: "574", name: "ADORAREI" },
  { number: "575", name: "TE ADORAMOS" },
  { number: "576", name: "REUNIMO-NOS AQUI PRA TE ADORAR" },
  { number: "577", name: "GLÓRIA E ALELUIA" },
  { number: "578", name: "HOJE O SENHOR DERRAMOU" },
  { number: "579", name: "SENHOR, EU NÃO SEI CONTAR" },
  { number: "580", name: "NOS PROSTREMOS AOS SEUS PÉS" },
  { number: "581", name: "PAI DE AMOR, GOSTO TANTO DE TI" },
  { number: "582", name: "CANTAREI AO AMOR DOS AMORES" },
  { number: "583", name: "Ó GRANDE DEUS" },
  { number: "584", name: "EU TE AMO, MEU JESUS" },
  { number: "585", name: "FONTE DA VIDA" },
  { number: "586", name: "Ó PROFUNDIDADE DAS RIQUEZAS" },
  { number: "587", name: "Ó JESUS, EXALTAR-TE-EI" },
  { number: "588", name: "HÁ UM NOME QUE RELUZ" },
  { number: "589", name: "JESUS TÃO BELO" },
  { number: "590", name: "AO CORDEIRO" },
  { number: "591", name: "GLÓRIA PRA SEMPRE AO CORDEIRO DE DEUS" },
  { number: "592", name: "ALELUIA! MUITAS VOZES DE ANJOS" },
  { number: "593", name: "A CRISTO COROAI" },
  { number: "594", name: "NA EXPRESSÃO DESTE LOUVOR" },
  { number: "595", name: "MAJESTADE, GLÓRIA E MAJESTADE" },
  { number: "596", name: "ÉS MAJESTADE" },
  { number: "597", name: "CANTAREI, CANTAREI HOSANA (VIVA O REI)" },
  { number: "598", name: "HÁ UM SÓ QUE É DIGNO" },
  { number: "599", name: "JESUS, TE ENTRONIZAMOS AQUI ENTRE NÓS" },
  { number: "600", name: "JESUS, TE ENTRONIZAMOS" },
  { number: "601", name: "AO QUE ESTÁ NO TRONO" },
  { number: "602", name: "SANTO É O QUE ESTÁ NO TRONO" },
  { number: "603", name: "LOUVAREI AO MEU SENHOR" },
  { number: "604", name: "O MEU LOUVOR É FRUTO" },
  { number: "605", name: "NOSSO DEUS É SOBERANO" },
  { number: "606", name: "O CRIADOR DO UNIVERSO" },
  { number: "607", name: "A DEUS SEJA O LOUVOR..." },
  { number: "608", name: "DEUS DOS EXÉRCITOS DE ISRAEL" },
  { number: "609", name: "SENHOR, MEU DEUS, QUANDO EU MARAVILHADO" },
  { number: "610", name: "SANTO! SANTO! SANTO! DEUS ONIPOTENTE!" },
  { number: "611", name: "JESUS, DEUS SANTO, SANTO, SANTO!" },
  { number: "612", name: "SANTO, SANTO, SANTO, Ó DEUS DE GLÓRIA E PODER" },
  { number: "613", name: "DAI GLÓRIA A DEUS" },
  { number: "614", name: "A DEUS DEMOS GLÓRIA" },
  { number: "615", name: "LOUVOR E GLÓRIA" },
  { number: "616", name: "AO DEUS DE AMOR E DE IMENSA BONDADE" },
  { number: "617", name: "O MEU CORAÇÃO SE REGOZIJA NO SENHOR" },
  { number: "618", name: "CANTAREI AO MEU SENHOR ENQUANTO EU VIVER" },
  { number: "619", name: "VEM, DERRAMA A PAZ" },
  { number: "620", name: "ESTAMOS AQUI, Ó DEUS" },
  { number: "621", name: "ADORAR-TE" },
  { number: "622", name: "A BELEZA DA TUA SANTIDADE" },
  { number: "623", name: "EU QUERO CANTAR DE GOZO E DE PAZ" },
  { number: "624", name: "A MINHA ALMA ENGRANDECE" },
  { number: "625", name: "DIGNO É JESUS" },
  { number: "626", name: "OH! CONTEMPLAI" },
  { number: "627", name: "NÓS TE ADORAMOS, SENHOR" },
  { number: "628", name: "SANTO É SEU NOME" },
  { number: "629", name: "QUE ALEGRIA" },
  { number: "630", name: "SAUDAI O NOME DE JESUS" },
  { number: "631", name: "SE EXALTADO Ó DEUS" },
  { number: "632", name: "MUITOS ANJOS LOUVAM" },
  { number: "633", name: "TE EXALTAREMOS" },
  { number: "634", name: "GLORIOSO ÉS, JESUS" },
  { number: "635", name: "ENTRONIZADO ESTÁS ENTRE AS NAÇÕES" },
  { number: "636", name: "LOUVAI A JESUS" },
  { number: "637", name: "TODA A TERRA TE EXALTA" },
  { number: "638", name: "JESUS VEIO E SALVOU-ME" },
  { number: "639", name: "MOTIVOS TENHO PRA LOUVAR-TE" },
  { number: "640", name: "MEU LOUVOR É SÓ PRA TI" },
  { number: "641", name: "A LUZ DO MUNDO" },
  { number: "642", name: "EM NOSSOS LÁBIOS" },
  { number: "643", name: "TODO LOUVOR SEJA DADO A DEUS" },
  { number: "644", name: "LOUVAMOS-TE Ó DEUS" },
  { number: "645", name: "COROAI" },
  { number: "646", name: "AGRADECIDOS SOMOS A TI" },
  { number: "647", name: "SANTO, SANTO, SANTO, É O SENHOR" },
  { number: "648", name: "O SENHOR É O MEU PASTOR (MINH'ALMA CANTARÁ)" },
  { number: "649", name: "TE LOUVAMOS, SENHOR" },
  { number: "650", name: "Ó VINDE E ADOREMOS" },
  { number: "651", name: "AMO AO SENHOR" },
  { number: "652", name: "LEVANTAI-VOS, Ó PORTAIS ETERNOS" },
  { number: "653", name: "ALELUIA (SL. 113)" },
  { number: "654", name: "GRANDE É O SENHOR E MUI DIGNO DE SER LOUVADO" },
  { number: "655", name: "LOUVAI, SERVOS DO SENHOR" },
  { number: "656", name: "GRANDE É O SENHOR" },
  { number: "657", name: "OS CÉUS PROCLAMAM" },
  { number: "658", name: "MEDITAREI NAS MARAVILHAS DO SENHOR" },
  { number: "659", name: "CELEBRAI COM JÚBILO AO SENHOR" },
  { number: "660", name: "O MEU CORAÇÃO" },
  { number: "661", name: "ÉS O MAIS FORMOSO, JESUS" },
  { number: "662", name: "ONIPOTENTE JESUS" },
  { number: "663", name: "LOUVAI AO SENHOR TODAS AS NAÇÕES" },
  { number: "664", name: "QUÃO AMÁVEIS SÃO" },
  { number: "665", name: "BENDIZEI AO SENHOR" },
  { number: "666", name: "TAL QUAL ESTOU" },
  { number: "667", name: "JUSTO ÉS, SENHOR" },
  { number: "668", name: "UM POBRE CEGO" },
  { number: "669", name: "DEUS DOS ANTIGOS" },
  { number: "670", name: "SE PAZ, A MAIS DOCE" },
  { number: "671", name: "OUVE, POIS, ISRAEL" },
  { number: "672", name: "MEU SERVO, NÃO TEMAS" },
  { number: "673", name: "Ó PAI, EU QUERIA TANTO VER (AUTOR DA MINHA FÉ)" },
  { number: "674", name: "EU NÃO SEI QUAL SERÁ MEU LOUVOR" },
  { number: "675", name: "NA ETERNIDADE" },
  { number: "676", name: "Ó VINDE ADORAR" },
  { number: "677", name: "A TI, QUE HABITAS ENTRE OS QUERUBINS" },
  { number: "678", name: "TUA GLÓRIA ENCHE TODA A TERRA" },
  { number: "679", name: "EIS A ESCRAVA RESGATADA" },
  { number: "680", name: "TEU NOME É PRA MIM, SENHOR" },
  { number: "681", name: "NOSSO LOUVOR" },
  { number: "682", name: "A JESUS SEJA DADA TODA GLÓRIA" },
  { number: "683", name: "JESUS CRISTO VOLTARÁ" },
  { number: "684", name: "ELE É O REI DOS REIS" },
  { number: "685", name: "PERFEITO AMOR EU CONHECI" },
  { number: "686", name: "QUANDO JESUS PROVOU O SEU AMOR POR MIM" },
  { number: "687", name: "QUEM É COMO TU?" },
  { number: "688", name: "CRISTO JÁ RESSUSCITOU" },
  { number: "689", name: "AMOR, QUE POR AMOR DESCESTE!" },
  { number: "690", name: "DA IGREJA O FUNDAMENTO É CRISTO" },
  { number: "691", name: "AO DEUS DE ABRAÃO" },
  { number: "692", name: "COMIGO HABITA, Ó DEUS!" },
  { number: "693", name: "DORMINDO NO MEU LEITO (JERUSALÉM, CIDADE SANTA)" },
  { number: "694", name: "JERUSALÉM ETERNA" },
  { number: "695", name: "JERUSALÉM EXCELSA" },
  { number: "696", name: "NA TERRA ABENÇOADA" },
  { number: "697", name: "OUVI O SALVADOR DIZER" },
  { number: "698", name: "TU, Ó DEUS, É TODA A GRANDEZA" },
  { number: "699", name: "QUE GRANDE REUNIÃO CONVOCADA ALI (JESUS DE NAZARÉ)" },
  { number: "700", name: "ESTÊVÃO AVISTOU" },
  { number: "701", name: "AS TUAS MÃOS DIRIGEM MEU DESTINO" },
  { number: "702", name: "OS CÉUS EM BREVE SE ABRIRÃO" },
  { number: "703", name: "SERÁ DE MANHÃ" },
  { number: "704", name: "SENHOR, SE ESTIVESSES AQUI (LÁZARO)" },
  { number: "705", name: "GRANDIOSO, SENHOR, OS TEUS FEITOS! (GRATIDÃO)" },
  { number: "706", name: "DESTE MUNDO ESCRAVO FUI" },
  { number: "707", name: "EU CONFIO EM TI, SENHOR" },
  { number: "708", name: "OUVI NO CÉU (BODAS DO CORDEIRO)" },
  { number: "709", name: "RESPLANDECE, Ó JERUSALÉM" },
  { number: "710", name: "O MEU VIVER É CRISTO" },
  { number: "711", name: "TUA GRAÇA ME BASTA, Ó SENHOR" },
  { number: "712", name: "AO FINDAR O LABOR DESTA VIDA (A ÚLTIMA HORA)" },
  { number: "713", name: "CAREÇO DE JESUS" },
  { number: "714", name: "COM TUA MÃO SEGURA BEM A MINHA (AMPARO DIVINO)" },
  { number: "715", name: "DEUS VOS GUARDE PELO SEU PODER" },
  { number: "716", name: "ENQUANTO, Ó SALVADOR, TEU LIVRO LER" },
  { number: "717", name: "A TERRA SEMEAMOS" },
  { number: "718", name: "GUIA, Ó CRISTO, MINHA NAU" },
  { number: "719", name: "AVANTE, AVANTE, Ó CRENTES" },
  { number: "720", name: "AS GRUTAS, AS ROCHAS IMENSAS (UM HINO AO SENHOR)" },
  { number: "721", name: "PROCLAMAI A TODO O MUNDO QUE O SENHOR É REI" },
  { number: "722", name: "A DEUS, SUPREMO CRIADOR" },
  { number: "723", name: "CRISTO PODE HOJE VIR " },
  { number: "724", name: "EIS OS MILHÕES" },
  { number: "725", name: "EU PERDIDO PECADOR" },
  { number: "726", name: "QUANDO A TEMPESTADE RUGE" },
  { number: "727", name: "EIS QUE ABRO A PORTA" },
  { number: "728", name: "NOSSA GRATIDÃO" },
  { number: "729", name: "OS TEUS ANJOS TE EXALTAM" },
  { number: "730", name: "SÓ TU NOS FAZES VENCEDORES" },
  { number: "731", name: "SEQUÊNCIA DE LOUVORES Nº 1" },
  { number: "732", name: "SEQUÊNCIA DE LOUVORES Nº 2" },
  { number: "733", name: "SEQUÊNCIA DE LOUVORES Nº 3" },
  { number: "734", name: "A VIDA DE MINHA ALMA" },
  { number: "735", name: "SEU NOME É JESUS" },
  { number: "736", name: "CRISTO É A RESPOSTA" },
  { number: "737", name: "SE ESTÁS CANSADO" },
  { number: "738", name: "GLÓRIA, GLÓRIA" },
  { number: "739", name: "EU TENHO UM TESOURO" },
  { number: "740", name: "EU TENHO UM DEUS MUI, MUI, MUI GRANDE" },
  { number: "741", name: "NÃO HÁ DEUS TÃO GRANDE COMO TU" },
  { number: "742", name: "NO CÉU HÁ PORTAS ABERTAS" },
  { number: "743", name: "VENCEREI, SIM" },
  { number: "744", name: "VITÓRIA DEUS DARÁ A MIM, EU SEI" },
  { number: "745", name: "É DEUS QUEM NOS TEM DADO A VITÓRIA" },
  { number: "746", name: "JESUS É O AMIGO MELHOR" },
  { number: "747", name: "SENHOR, MANDA PODER" },
  { number: "748", name: "QUE CALOR É ESTE EM VOLTA DO ALTAR?" },
  { number: "749", name: "MANDA FOGO, SENHOR" },
  { number: "750", name: "DEIXA A GLÓRIA DE DEUS BRILHAR" },
  { number: "751", name: "EU LOUVAREI, EU LOUVAREI" },
  { number: "752", name: "ESTOU ALEGRE" },
  { number: "753", name: "A NOIVA É A IGREJA" },
  { number: "754", name: "EU VEREI A ÁRVORE DA VIDA" },
  { number: "755", name: "SOMENTE PELA FÉ" },
  { number: "756", name: "QUEM CANTAR AQUI SE ALEGRARÁ" },
  { number: "757", name: "COMO ACONTECEU EM JERUSALÉM" },
  { number: "758", name: "ESTA ALEGRIA NÃO VAI MAIS SAIR" },
  { number: "759", name: "NUNCA MAIS, NUNCA MAIS" },
  { number: "760", name: "DO CÉU VIRÁ" },
  { number: "761", name: "CADA PASSO QUE DÁS" },
  { number: "762", name: "O CÉU É UM LUGAR MARAVILHOSO" },
  { number: "763", name: "JESUS É TUDO PRA MIM" },
  { number: "764", name: "NÓS VAMOS LÁ, IRMÃOS" },
  { number: "765", name: "LÁ NO CÉU TODOS CANTAM ALELUIA" },
  { number: "766", name: "NO DIA DA GRANDE GLÓRIA" },
  { number: "767", name: "CONTA PRA JESUS ONDE É A TUA DOR" },
  { number: "768", name: "A VITÓRIA DESTA IGREJA É ORAÇÃO" },
  { number: "769", name: "O GRANDE RELÓGIO" },
  { number: "770", name: "POR QUE DEIXAR QUE AS ÂNSIAS" },
  { number: "771", name: "CAMINHANDO VOU PARA CANAÃ" },
  { number: "772", name: "CADA DIA ME DIRIGE" },
  { number: "773", name: "ABRA A PORTA, VENHA VER" },
  { number: "774", name: "CHEGADO À CRUZ DO MEU SALVADOR" },
  { number: "775", name: "SUBINDO PARA O CÉU EU VOU" },
  { number: "776", name: "CERTA VEZ EU ORANDO" },
  { number: "777", name: "COMO AS ÁGUAS" },
  { number: "778", name: "DEUS ESTÁ AQUI" },
  { number: "779", name: "ABRE A PORTA DO TEU CORAÇÃO" },
  { number: "780", name: "CANTAREI, CANTAREI AS MISERICÓRDIAS" },
  { number: "781", name: "SÓ O PODER DE DEUS" },
  { number: "782", name: "TENHO NOVA VIDA" },
  { number: "783", name: "FELIZ, FELIZ EU SOU" },
  { number: "784", name: "CANTAI AO SENHOR UM CÂNTICO NOVO" },
  { number: "785", name: "ESTOU CONFIANDO" },
  { number: "786", name: "QUE AS PALAVRAS DA MINHA BOCA" },
  { number: "787", name: "ARDE-ME EM FOGO MINH'ALMA ESTÁ" },
  { number: "788", name: "IGREJA, TU VAIS SUBIR" },
  { number: "789", name: "NA PRESENÇA DE JESUS" },
  { number: "790", name: "AQUELE QUE HABITA NO ESCONDERIJO" },
  { number: "791", name: "EU QUERO MAIS E MAIS DE CRISTO" },
  { number: "792", name: "LOUVANDO A DEUS" },
  { number: "793", name: "MESA PREPARADA" },
  { number: "794", name: "JESUS LIBERTOU" },
  { number: "731-A", name: "DESDE O DIA EM QUE ACEITEI JESUS" },
  { number: "731-B", name: "A MINHA ALMA ESTÁ CHEIA DE PAZ" },
  { number: "731-C", name: "SOU FELIZ PORQUE SOU DE CRISTO" },
  { number: "731-D", name: "NA CASA DE MEU PAI NÃO HÁ TRISTEZA" },
  { number: "731-E", name: "É ISTO QUE ME FAZ CANTAR" },
  { number: "731-F", name: "GOZO EU TENHO EM JESUS" },
  { number: "731-G", name: "JESUS É MARAVILHOSO!" },
  { number: "732-A", name: "ESTAMOS MUITO ALEGRE" },
  { number: "732-B", name: "EU QUERO ANDAR NAS RUAS DE OURO" },
  { number: "732-C", name: "EU TENHO UMA COROA LÁ NO CÉU" },
  { number: "732-D", name: "EU SOU FELIZ PORQUE A BÍBLIA DIZ" },
  { number: "732-E", name: "O NOME DE JESUS É DOCE" },
  { number: "732-F", name: "COMO É BOM DEIXAR ESTE MUNDO" },
  { number: "733-A", name: "EU TENHO UM AMIGO QUE ME AMA" },
  { number: "733-B", name: "A VIDA, A VIDA É JESUS" },
  { number: "733-C", name: "MEU CORAÇÃO CONTENTE ESTÁ" },
  { number: "733-D", name: "EU SÓ CONFIO NO SENHOR" },
  { number: "CONTRA CAPA", name: "AQUILO QUE FUI NÃO SOU MAIS" },
  { number: "GL", name: "GRUPO DE LOUVOR" },
];

export const CIAS_DATA = [
  { number: "1", name: "MEU DEUS, MEU PAI" },
  { number: "2", name: "PAI, ESTOU A TE CLAMAR" },
  { number: "3", name: "CLAMO, Ó SENHOR, POR TEU SANGUE" },
  { number: "4", name: "CLAMO, Ó SENHOR" },
  { number: "5", name: "ESTOU AQUI PRA CONFESSAR" },
  { number: "6", name: "PERDOA-ME, SENHOR" },
  { number: "7", name: "É TEU SANGUE, MEU SENHOR JESUS" },
  { number: "8", name: "DIANTE DO TEU ALTAR" },
  { number: "9", name: "DOBRO OS MEUS JOELHOS" },
  { number: "10", name: "CLAMA, Ó IGREJA" },
  { number: "11", name: "CLAMO A TI, MEU SENHOR E PAI (UMA NOVA CANÇÃO)" },
  { number: "12", name: "PERDOA-ME, SENHOR, SEGUNDO O TEU AMOR" },
  { number: "13", name: "PURIFICADO COM SANGUE ESTOU" },
  { number: "14", name: "TE SUPLICO, Ó DEUS, EM ORAÇÃO" },
  { number: "15", name: "JESUS, VEM ME ABENÇOAR" },
  { number: "16", name: "PAI CELESTE" },
  { number: "17", name: "QUANDO FALO COM DEUS" },
  { number: "18", name: "BUSCAI AO SENHOR" },
  { number: "19", name: "QUANDO DAVI AO SENHOR ORAVA" },
  { number: "20", name: "QUANDO ORO AO SENHOR" },
  { number: "21", name: "SANTO, JUSTO, PRÍNCIPE DA VIDA" },
  { number: "22", name: "FAZE ORAÇÃO" },
  { number: "23", name: "QUANDO ISRAEL SAIU DO EGITO" },
  { number: "24", name: "UMA OVELHINHA DE JESUS EU SOU" },
  { number: "25", name: "ONDE QUER QUE TU FORES IREI, JESUS" },
  { number: "26", name: "EU SOU UMA OVELHINHA" },
  { number: "27", name: "ELE É A RAIZ" },
  { number: "28", name: "SOU UMA CRIANÇA FELIZ" },
  { number: "29", name: "JESUS, QUANDO ME LEMBRO" },
  { number: "30", name: "ELE VIVE EM MIM" },
  { number: "31", name: "EU QUERO SER O SAL DA TERRA" },
  { number: "32", name: "PRÍNCIPE DA PAZ" },
  { number: "33", name: "CRISTO, MEU BOM MESTRE" },
  { number: "34", name: "TENHO UM SENHOR MUITO FORTE" },
  { number: "35", name: "QUERO SER COMO DAVI" },
  { number: "36", name: "EU QUERO ANDAR SEMPRE COM JESUS" },
  { number: "37", name: "NO MEU CORAÇÃO HÁ UM TESOURO" },
  { number: "38", name: "TENHO UM CORAÇÃO ALEGRE" },
  { number: "39", name: "NA AREIA NÃO QUERO CONSTRUIR" },
  { number: "40", name: "QUERO OUVIR (MEU QUERER)" },
  { number: "41", name: "A MINHA FIRME E ESTÁ" },
  { number: "42", name: "MINHA VIDA E MEU CORAÇÃO" },
  { number: "43", name: "SOU FELIZ" },
  { number: "44", name: "SOU SERVO DO SENHOR" },
  { number: "45", name: "JESUS RESSUSCITOU! (MEU AMIGO JESUS)" },
  { number: "46", name: "COMO É BOM SERVIR A DEUS" },
  { number: "47", name: "TENHO NO MEU CORAÇÃO" },
  { number: "48", name: "JESUS CRISTO É O AMADO" },
  { number: "49", name: "A MINHA ALEGRIA É CRESCER COM O MEU SENHOR!" },
  { number: "50", name: "DO ALTO CÉU" },
  { number: "51", name: "EIS-ME AQUI, SENHOR EM TEU ALTAR" },
  { number: "52", name: "SEU NOME É MARAVILHOSO" },
  { number: "53", name: "É BOM, É BOM DEMAIS" },
  { number: "54", name: "COMO É BOM SABER" },
  { number: "55", name: "É SOMENTE TEU MEU CORAÇÃO" },
  { number: "56", name: "CRISTO É O SENHOR" },
  { number: "57", name: "HÁ UMA LINDA CANÇÃO DE AMOR" },
  { number: "58", name: "VIVER É TÃO LINDO" },
  { number: "59", name: "O NOME DO MEU SENHOR" },
  { number: "60", name: "DEUS FALOU COMIGO" },
  { number: "61", name: "SEI QUE NA CRUZ SEU SANGUE VERTEU" },
  { number: "62", name: "E TÃO TRISTE NÃO VER A LUZ (O CEGO BARTIMEU)" },
  { number: "63", name: "TEM BOM ÂNIMO, POBRE PECADOR" },
  { number: "64", name: "EU VOU CONTAR UMA HISTÓRIA (ZAQUEU)" },
  { number: "65", name: "ONDE NASCEU JESUS?" },
  { number: "66", name: "NASCEU UM NOVO DIA" },
  { number: "67", name: "MARAVILHA É O AMOR DE DEUS" },
  { number: "68", name: "VEM PARA O MEIO (ÁGUAS DA SALVAÇÃO)" },
  { number: "69", name: "VOCÊ SABE O QUE É SALVAÇÃO?" },
  { number: "70", name: "O DIA DO SENHOR VIRÁ (O SOL DA JUSTIÇA)" },
  { number: "71", name: "JESUS VIU A MULTIDÃO (A MULTIPLICAÇÃO)" },
  { number: "72", name: "TU ÉS O CRISTO, O FILHO DO DEUS VIVO" },
  { number: "73", name: "DA ETERNIDADE À ETERNIDADE" },
  { number: "74", name: "AQUILO QUE MELHOR EXISTE" },
  { number: "75", name: "VOCÊ SABE QUEM FOI JOÃO BATISTA?" },
  { number: "76", name: "JESUS FALOU QUE O CÉU É PRA MIM" },
  { number: "77", name: "VOU CONTAR-VOS DE JESUS" },
  { number: "78", name: "O SENHOR É A MINHA LUZ E A MINHA SALVAÇÃO" },
  { number: "79", name: "DEUS AMA VOCÊ" },
  { number: "80", name: "EXISTE UM LUGAR" },
  { number: "81", name: "QUANDO OUVI JESUS ME CHAMAR" },
  { number: "82", name: "JESUS VEM NOS BUSCAR" },
  { number: "83", name: "FOI NO CAMINHO PARA DAMASCO" },
  { number: "84", name: "QUERES SER FELIZ?" },
  { number: "85", name: "NESTE DIA ESPECIAL" },
  { number: "86", name: "UM DIA MORREU O MEU JESUS" },
  { number: "87", name: "O SENHOR É O BOM PASTOR" },
  { number: "88", name: "VOU CONTAR PARA VOCÊ UMA HISTÓRIA ESPECIAL" },
  { number: "89", name: "CERTO HOMEM, PRÍNCIPE DOS JUDEUS (NICODEMOS)" },
  { number: "90", name: "ELE MORREU, MAS RESSURGIU" },
  { number: "91", name: "TENHO ALGO PRA VOCÊ" },
  { number: "92", name: "JESUS CURA E SALVA" },
  { number: "93", name: "JESUS TE AMA" },
  { number: "94", name: "AQUELE QUE TEM SEDE" },
  { number: "95", name: "DO PÃO DO CÉU" },
  { number: "96", name: "SONHEI COM JESUS ESTA NOITE" },
  { number: "97", name: "JESUS É O CAMINHO" },
  { number: "98", name: "EU ABRI MEU CORAÇÃO" },
  { number: "99", name: "NO MEU CORAÇÃO" },
  { number: "100", name: "CRISTO SENTE AMOR POR MIM" },
  { number: "101", name: "JESUS ME AMA" },
  { number: "102", name: "DAS MARAVILHAS QUE A BÍBLIA CONTÉM" },
  { number: "103", name: "VINDE, MENINOS" },
  { number: "104", name: "NO CAMINHO ELE ME GUIARÁ" },
  { number: "105", name: "HAVEREMOS DE CHEGAR" },
  { number: "106", name: "JESUS CRISTO É O CAMINHO" },
  { number: "107", name: "EU QUERO CANTAR" },
  { number: "108", name: "HOJE É UM GRANDE DIA" },
  { number: "109", name: "CANTA ALEGREMENTE, Ó FILHA DE SIÃO" },
  { number: "110", name: "EU TUDO POSSO NAQUELE QUE ME FORTALECE" },
  { number: "111", name: "ENTREGA O TEU CAMINHO" },
  { number: "112", name: "CONSOLA-ME, ESPÍRITO SANTO" },
  { number: "113", name: "TUA MÃO É PODEROSA" },
  { number: "114", name: "O SENHOR É QUEM CUIDA DE MIM" },
  { number: "115", name: "JESUS, O BOM PASTOR" },
  { number: "116", name: "SOBRE AS ONDAS" },
  { number: "117", name: "DEITADA NA RELVA UMA FELIZ OVELHA" },
  { number: "118", name: "UMA ÂNCORA SEGURA" },
  { number: "119", name: "JESUS, O MELHOR AMIGO" },
  { number: "120", name: "PODERÁ CANTAR" },
  { number: "121", name: "MEU BARQUINHO" },
  { number: "122", name: "CRISTO É MEU AMIGO" },
  { number: "123", name: "NESTA BATALHA NÃO TEREIS QUE PELEJAR" },
  { number: "124", name: "O CÉU E A TERRA PASSARÃO" },
  { number: "125", name: "COM JESUS VENCEDOR SEREI" },
  { number: "126", name: "DEUS FORTE COMO JEOVÁ" },
  { number: "127", name: "CRISTO É VITÓRIA" },
  { number: "128", name: "CRISTO É MEU AMIGO, É MEU AMIGO" },
  { number: "129", name: "ONTEM, HOJE E PARA SEMPRE" },
  { number: "130", name: "MEU BOM PASTOR É CRISTO" },
  { number: "131", name: "COM CRISTO NO BARCO" },
  { number: "132", name: "MEU BARCO É PEQUENO" },
  { number: "133", name: "JESUS VÊ A SUA IGREJA" },
  { number: "134", name: "VOU CAMINHANDO PRA JERUSALÉM" },
  { number: "135", name: "FLUA EM MIM, SENHOR" },
  { number: "136", name: "LÂMPADA PARA MEUS PÉS" },
  { number: "137", name: "NÃO POR FORÇA" },
  { number: "138", name: "SOU UM SOLDADO DO BOM SALVADOR" },
  { number: "139", name: "DONS DO ESPÍRITO SANTO" },
  { number: "140", name: "UMA LUZ RESPLANDECENTE" },
  { number: "141", name: "QUEM IRÁ? (PRECIOSA SEMENTE)" },
  { number: "142", name: "COMO UMA FOLHA AO VENTO" },
  { number: "143", name: "TENHO UMA CANDEIA (CANDEIA ACESA)" },
  { number: "144", name: "NOVA ALIANÇA" },
  { number: "145", name: "REVELAÇÃO ABRE PRA VOCÊ" },
  { number: "146", name: "A IGREJA QUE ORA É VITORIOSA" },
  { number: "147", name: "EM TUAS PISADAS" },
  { number: "148", name: "ANDANDO EM ESPÍRITO" },
  { number: "149", name: "NÓS SOMOS UMA VOZ" },
  { number: "150", name: "CINCO SEIXOS" },
  { number: "151", name: "NO PRINCÍPIO ERA O VERBO" },
  { number: "152", name: "NAS BATALHAS SOU UM VENCEDOR" },
  { number: "153", name: "COMO NOÉ" },
  { number: "154", name: "COM O ESPÍRITO DE DEUS EM MINHA VIDA" },
  { number: "155", name: "QUERO ESTAR EM TUA PRESENÇA, Ó DEUS" },
  { number: "156", name: "SOMOS CIDADÃOS DO CÉU" },
  { number: "157", name: "ESTE MUNDO NÃO É MEU LUGAR" },
  { number: "159", name: "SERVO DO SENHOR EU SOU" },
  { number: "160", name: "EXISTEM SEGREDOS NA TUA PALAVRA" },
  { number: "161", name: "TU ÉS PRA MIM UM VASO ESCOLHIDO" },
  { number: "162", name: "ANDAI NA MINHA PRESENÇA" },
  { number: "163", name: "DÁ-ME UM CORAÇÃO CHEIO DO TEU AMOR" },
  { number: "164", name: "DÁ-ME UM CORAÇÃO HUMILDE E RETO" },
  { number: "165", name: "QUERO SER SANTO PARA O SENHOR" },
  { number: "166", name: "BRILHANDO, BRILHANDO" },
  { number: "167", name: "DANIEL NA COVA DOS LEÕES" },
  { number: "168", name: "JESUS CHAMA OS SEUS MINISTROS" },
  { number: "169", name: "SETE CARTAS" },
  { number: "170", name: "NÓS SOMOS A CARTA DE CRISTO" },
  { number: "171", name: "SOU O SANTO" },
  { number: "172", name: "QUATRO COISAS TÃO PEQUENINAS" },
  { number: "173", name: "OUÇO O CLAMOR DO BOM PASTOR" },
  { number: "174", name: "A TUA PALAVRA É SEMENTE" },
  { number: "175", name: "UM CERTO PASTORZINHO" },
  { number: "176", name: "CRIA EM MIM, Ó DEUS" },
  { number: "177", name: "FALA AO MEU CORAÇÃO, JESUS" },
  { number: "178", name: "DISSE JESUS AOS JUDEUS" },
  { number: "179", name: "ORAR FAZ BEM" },
  { number: "180", name: "QUERO SER FIEL (JESUS ESTÁ VIVO)" },
  { number: "181", name: "JERUSALÉM, CIDADE DO MEU REI" },
  { number: "182", name: "QUERO VIVER PARA SEMPRE COM JESUS" },
  { number: "183", name: "UM NOVO CÉU, UMA NOVA TERRA SE FARÁ" },
  { number: "184", name: "NO EXPRESSO VIAJAMOS" },
  { number: "185", name: "HÁ UMA LINDA MORADA" },
  { number: "186", name: "NOSSAS VIDAS SÃO MUDADAS" },
  { number: "187", name: "VARÕES GALILEUS" },
  { number: "188", name: "JERUSALÉM ANSEIO VER" },
  { number: "189", name: "UM DIA A IGREJA SUBIRÁ" },
  { number: "190", name: "IGREJA, CORPO DE CRISTO" },
  { number: "191", name: "A NOIVA AMADA DO CORDEIRO" },
  { number: "192", name: "VOU PRA JERUSALÉM" },
  { number: "193", name: "HÁ UMA IGREJA" },
  { number: "194", name: "NA NOVA JERUSALÉM" },
  { number: "195", name: "EM BREVE ESTAREMOS NA GLÓRIA" },
  { number: "196", name: "JESUS NOS PROMETEU" },
  { number: "197", name: "MARANATA! VEM, SENHOR JESUS" },
  { number: "198", name: "O DIA ESTÁ CHEGANDO" },
  { number: "199", name: "AGUARDANDO A ORIENTAÇÃO DO SENHOR" },
  { number: "200", name: "VOU PARA O MEU LAR" },
  { number: "201", name: "SOBRE AS NUVENS JESUS VEM" },
  { number: "202", name: "A RAABE VEIO A ORDEM" },
  { number: "203", name: "O FIO DE ESCARLATA E O MISTÉRIO" },
  { number: "204", name: "MARCHAI! MARCHAI!" },
  { number: "205", name: "A MINHA ALMA ESPERA" },
  { number: "206", name: "NO CÉU UM DIA NÓS VAMOS MORAR" },
  { number: "207", name: "JESUS PROMETEU NOS BUSCAR" },
  { number: "208", name: "EU QUERO IR PARA O CÉU" },
  { number: "209", name: "SE EU FALO DO GRANDE AMOR DO PAI" },
  { number: "210", name: "JESUS VOLTARÁ PRA ME BUSCAR (MARANATA)" },
  { number: "211", name: "OS DIAS ESTÃO PASSANDO" },
  { number: "212", name: "SEI QUE CRISTO VOLTARÁ" },
  { number: "213", name: "LÁ NO DOCE PORVIR" },
  { number: "214", name: "NÓS RECEBEREMOS LÁ NO CÉU" },
  { number: "215", name: "EIS QUE JESUS VEM NAS NUVENS" },
  { number: "216", name: "SOBRE AS NUVENS DESCERÁ (ELE VIRÁ)" },
  { number: "217", name: "VEREI MEU GRANDE REI" },
  { number: "218", name: "MARANATA" },
  { number: "219", name: "ELE VIRÁ NO MEIO DA NOITE" },
  { number: "220", name: "ONDE VIVE O REI DA GLÓRIA?" },
  { number: "221", name: "VAI RAIAR O DIA" },
  { number: "222", name: "DEUS HABITA NO MEIO DOS LOUVORES" },
  { number: "223", name: "PAI, TUA BELEZA ME ADMIRA" },
  { number: "224", name: "DEUS CRIOU OS CÉUS E A TERRA" },
  { number: "225", name: "EU VIM AQUI, SENHOR" },
  { number: "226", name: "IREI CANTAR E ADORAR O REI JESUS" },
  { number: "227", name: "A JESUS IREI LOUVAR" },
  { number: "228", name: "HOSANA AO FILHO DE DAVI" },
  { number: "229", name: "CANTAI ALEGREMENTE A DEUS" },
  { number: "230", name: "ESTA CANÇÃO" },
  { number: "231", name: "TODO SER QUE TEM FÔLEGO" },
  { number: "232", name: "HOJE EU NÃO QUERO PEDIR" },
  { number: "233", name: "NA CIDADE DE DAVI NASCEU O SALVADOR" },
  { number: "234", name: "SEI QUE SOU AMADO DO MEU SALVADOR" },
  { number: "235", name: "SENHOR, EU TE LOUVAREI" },
  { number: "236", name: "SENHOR DEUS, TU ÉS VARÃO DE GUERRA" },
  { number: "237", name: "MUITOS MOTIVOS TENHO" },
  { number: "238", name: "EU VOU CANTAR" },
  { number: "239", name: "JESUS É A NOSSA VITÓRIA" },
  { number: "240", name: "O SENHOR DOS EXÉRCITOS ESTÁ AQUI" },
  { number: "241", name: "EXALTAI, EXALTAI" },
];
export const AVULSOS_DATA = [
  { number: "001", name: "A COLHEITA FINAL" },
  { number: "002", name: "A ESPERANÇA" },
  { number: "003", name: "A MELHOR COISA" },
  { number: "004", name: "ABRE O CORAÇÃO" },
  { number: "005", name: "ALELUIA AO CORDEIRO" },
  { number: "006", name: "O JORDÃO EU NÃO PASSAREI SÓ" },
  { number: "007", name: "AO ORARMOS, SENHOR" },
  { number: "008", name: "AQUELE QUE HABITA" },
  { number: "009", name: "AQUI CHEGAMOS PELA FÉ" },
  { number: "010", name: "BARNABÉ" },
  { number: "011", name: "BEIJAR MEU JESUS" },
  { number: "012", name: "BÊNÇÃO" },
  { number: "013", name: "BENDIREI" },
  { number: "014", name: "BENDITA A HORA" },
  { number: "015", name: "CANAÃ É LOGO ALI" },
  { number: "016", name: "CHORA AOS PÉS DE JESUS" },
  { number: "017", name: "COM MEU CORAÇÃO" },
  { number: "018", name: "COMEÇANDO AQUI" },
  { number: "019", name: "COMO AGRADECER (MEU TRIBUTO)" },
  { number: "020", name: "COMO É IMPORTANTE MEU JESUS" },
  { number: "021", name: "COMO OVELHAS PERDIDAS" },
  { number: "022", name: "CORDEIRO DE DEUS" },
  { number: "023", name: "COROAI O REI" },
  { number: "024", name: "DESCANSA, Ó ALMA" },
  { number: "025", name: "DEUS, DEUS, DEUS" },
  { number: "026", name: "DEUS PREPAROU" },
  { number: "027", name: "DEUS TEM UM PLANO" },
  { number: "028", name: "DEVO A TI" },
  { number: "029", name: "DEIXA DEUS RESOLVER" },
  { number: "030", name: "DIREÇÃO" },
  { number: "031", name: "DOCE NOME" },
  { number: "032", name: "EIS QUE ESTOU VIVO" },
  { number: "033", name: "ELE É EXALTADO" },
  { number: "034", name: "ELE É O SENHOR JEOVÁ" },
  { number: "035", name: "EM ORAÇÃO EU ME ENTREGO" },
  { number: "036", name: "EU NÃO POSSO FUGIR DO TEU ESPÍRITO" },
  { number: "037", name: "EU QUERO IR TAMBÉM" },
  { number: "038", name: "EU QUERO MAIS E MAIS DE CRISTO" },
  { number: "039", name: "EU QUERO SENTIR" },
  { number: "040", name: "EU SOU" },
  { number: "041", name: "EU TE AMEI" },
  { number: "042", name: "EU VOU CANTAR DA GLÓRIA" },
  { number: "043", name: "EXALTADO" },
  { number: "044", name: "EXPIROU" },
  { number: "045", name: "EXALTAI O SANTO NOME" },
  { number: "046", name: "EXALTADO, Ó DEUS, SEJA O TEU NOME" },
  { number: "047", name: "É DE JOELHOS" },
  { number: "048", name: "ÉS UM REMIDO DE DEUS" },
  { number: "049", name: "FALA, SENHOR" },
  { number: "050", name: "FAZ DE NÓS UM" },
  { number: "051", name: "FICA AO MEU LADO" },
  { number: "052", name: "FINDA-SE ESTE DIA" },
  { number: "053", name: "A FORMOSA JERUSALÉM" },
  { number: "054", name: "GUIA-ME" },
  { number: "055", name: "GRAÇAS DOU POR ESTA VIDA" },
  { number: "056", name: "GRAÇAS SENHOR" },
  { number: "057", name: "GRANDE É O SENHOR, INCLINAI-VOS" },
  { number: "058", name: "GRANDE É O SENHOR, SANTO E JUSTO" },
  { number: "059", name: "GRANDE SENHOR, MARAVILHOSO ÉS" },
  { number: "060", name: "HÁ UM ÓLEO" },
  { number: "061", name: "HÁ UMA PÁTRIA NO ALÉM" },
  { number: "062", name: "HÁ UMA TERRA ALÉM DO RIO" },
  { number: "063", name: "HOJE AQUI" },
  { number: "064", name: "HINO NACIONAL" },
  { number: "065", name: "HOJE EU DESCOBRI" },
  { number: "066", name: "IGREJA PODEROSA" },
  { number: "067", name: "JERUSALÉM DE OURO" },
  { number: "068", name: "JESUS, VEM LOGO" },
  { number: "069", name: "JESUS, SEMPRE TE AMO" },
  { number: "070", name: "JESUS, SOMENTE TU" },
  { number: "071", name: "JESUS PASSOU SEU SANGUE AQUI" },
  { number: "072", name: "JUNTO A TI, QUERO ESTAR" },
  { number: "073", name: "LAMENTO DE ISRAEL" },
  { number: "074", name: "LOUVAI A DEUS, SENHOR" },
  { number: "075", name: "LOUVAI AO SENHOR (SALMO 150)" },
  { number: "076", name: "LOUVAMOS-TE" },
  { number: "077", name: "LOUVANDO A DEUS" },
  { number: "078", name: "LOUVOR E HONRA" },
  { number: "079", name: "MAIS PUREZA DÁ-ME" },
  { number: "080", name: "MAIS QUE MARAVILHOSO" },
  { number: "081", name: "MAIS QUE VENCEDORES" },
  { number: "082", name: "MAJESTOSO É O TEU NOME" },
  { number: "083", name: "MARAVILHA, OH! QUE MARAVILHA" },
  { number: "084", name: "MARAVILHOSO AMOR" },
  { number: "085", name: "MEU SENHOR JESUS" },
  { number: "086", name: "MIL GLÓRIAS" },
  { number: "087", name: "NÃO SAIAS SEM CRISTO" },
  { number: "088", name: "NESTA HORA EM ORAÇÃO" },
  { number: "089", name: "NO EXÍLIO" },
  { number: "090", name: "NÓS CANTAMOS SANTO" },
  { number: "091", name: "NO DIA DA GRANDE GLÓRIA" },
  { number: "092", name: "NOS MOMENTOS CRUÉIS E DIFÍCEIS" },
  { number: "093", name: "O NOVO CÉU" },
  { number: "094", name: "O ANJO DO EGITO" },
  { number: "095", name: "O CULTO HOJE VAI SER MARAVILHOSO" },
  { number: "096", name: "O FOGO RENOVADOR" },
  { number: "097", name: "O NOME DE CRISTO" },
  { number: "098", name: "O SENHOR É MINHA LUZ" },
  { number: "099", name: "O SENHOR É MINHA ROCHA" },
  { number: "100", name: "O SENHOR É O MEU PASTOR (SALMO 23)" },
  { number: "101", name: "O SENHOR É O MEU PASTOR (MARANATA! JESUS VEM!)" },
  { number: "102", name: "O SENHOR ESTÁ CUIDANDO DE VOCÊ" },
  { number: "103", name: "OH! VINDE ADORAR" },
  { number: "104", name: "Ó VÓS QUE TENDES SEDE" },
  { number: "105", name: "OLHAR SOMENTE A TI, SENHOR" },
  { number: "106", name: "ORAÇÃO PELA PÁTRIA" },
  { number: "107", name: "OS CÉUS DECLARAM A GLÓRIA DE DEUS" },
  { number: "108", name: "OS TEMPOS E COISAS SE MUDAM" },
  { number: "109", name: "PAI NOSSO" },
  { number: "110", name: "PAI QUE ESTÁS NO CÉU" },
  { number: "111", name: "PEGA A TUA PARTE" },
  { number: "112", name: "PELO MUNDO PERDIDO" },
  { number: "113", name: "PELO VALE ESCURO" },
  { number: "114", name: "PRIMEIRO EU QUERO VER MEU SALVADOR" },
  { number: "115", name: "PROCLAME A GLÓRIA DO SENHOR" },
  { number: "116", name: "QUANDO CHEGO EM TUA CASA" },
  { number: "117", name: "QUANDO ENTREI NESTE LUGAR" },
  { number: "118", name: "QUANDO VOCÊ FOI FORMADO (AMOR INCONDICIONAL)" },
  { number: "119", name: "QUEM É ESTE POVO" },
  { number: "120", name: "QUEM É ESTE QUE VEM" },
  { number: "121", name: "QUEM SÃO ESTES DE BRANCOS VESTIDOS" },
  { number: "122", name: "QUEM SOU EU" },
  { number: "123", name: "QUERO ANDAR DE VALOR EM VALOR" },
  { number: "124", name: "QUERO CANTAR ESSE AMOR" },
  { number: "125", name: "QUERO BUSCAR E PEDIR AO SENHOR" },
  { number: "126", name: "QUERO O SALVADOR" },
  { number: "127", name: "QUERO VER O SOL JÁ CANSADO BRILHAR" },
  { number: "128", name: "REFÚGIO VERDADEIRO" },
  { number: "129", name: "SABE FILHO" },
  { number: "130", name: "SANSÃO" },
  { number: "131", name: "SANTO, DEUS DOS EXÉRCITOS" },
  { number: "132", name: "SANTO, JUSTO, MISERICORDIOSO" },
  { number: "133", name: "SHALOM" },
  { number: "134", name: "SEI QUE ÉS FIEL, JESUS" },
  { number: "135", name: "SENHOR, NADA SOMOS NESTE MUNDO" },
  { number: "136", name: "SERVO DEVEDOR" },
  { number: "137", name: "SÓ EM JESUS" },
  { number: "138", name: "SOU ESTRANGEIRO" },
  { number: "139", name: "SUPREMO DEUS (DIGNO DE LOUVOR)" },
  { number: "140", name: "TEUS SONHOS" },
  { number: "141", name: "VEREI JESUS" },
  { number: "142", name: "VEREI MEU REDENTOR" },
  { number: "143", name: "VINDE A MIM" },
  { number: "144", name: "VINDE APÓS MIM" },
  { number: "145", name: "VOZES LINDAS NUNCA OUVIDAS" },
  { number: "146", name: "SE NOS CEGA O SOL ARDENTE" },
  { number: "147", name: "SALVO DE GRAÇA" },
  { number: "148", name: "A MINH’ALMA ESPERA" },
  { number: "149", name: "A MINH’ALMA SE ENCHE DA GRAÇA" },
  { number: "150", name: "A VITÓRIA É NOSSA PELO SANGUE DE JESUS" },
  { number: "151", name: "AO NOSSO DEUS" },
  { number: "152", name: "AO ÚNICO" },
  { number: "153", name: "ADORAÇÃO" },
  { number: "154", name: "ÁGUAS QUE SARAM" },
  { number: "155", name: "AJUNTAMENTO" },
  { number: "156", name: "ALEGREI-ME" },
  { number: "157", name: "ALGUÉM ME FALOU DO AMOR" },
  { number: "158", name: "AMOR SEM FIM" },
  { number: "159", name: "ANDAM PROCURANDO A RAZÃO DE VIVER" },
  { number: "160", name: "ATRAVÉS DO TEU SANGUE" },
  { number: "161", name: "BEM AVENTURADO (SALMO 89)" },
  { number: "162", name: "BENDITO SEJA DEUS" },
  { number: "163", name: "BUSCAI PRIMEIRO O REINO DE DEUS" },
  { number: "164", name: "BRILHA JESUS" },
  { number: "165", name: "CANTO DE VITÓRIA" },
  { number: "166", name: "COMO NASCE A FLOR" },
  { number: "167", name: "CONFISSÃO" },
  { number: "168", name: "CONHECI O MUNDO MAU" },
  { number: "169", name: "CHEGOU A HORA" },
  { number: "170", name: "DAI LOUVORES" },
  { number: "171", name: "DE TODAS AS TRIBOS" },
  { number: "172", name: "DEIXA O MEU POVO IR" },
  { number: "173", name: "DESDE O DIA QUE ACEITEI JESUS" },
  { number: "174", name: "DESEJADO DAS NAÇÕES" },
  { number: "175", name: "DEUS TEM CUIDADO DE NÓS" },
  { number: "176", name: "DEUS SOMENTE DEUS" },
  { number: "177", name: "DEUS DE MILAGRES" },
  { number: "178", name: "DIGO AO SENHOR" },
  { number: "179", name: "DO SENHOR OUÇO A SUAVE VOZ" },
  { number: "180", name: "ÉS ORVALHO" },
  { number: "181", name: "E O MESMO DEUS DA PAZ" },
  { number: "182", name: "É TEU POVO" },
  { number: "183", name: "ÉS MEU TESOURO" },
  { number: "184", name: "EU, O SENHOR" },
  { number: "185", name: "EU TE AMO MAIS QUE A ABELHA AMA A FLOR" },
  { number: "186", name: "EU TENHO UM PAI (ADOÇÃO)" },
  { number: "187", name: "EU TE LOUVAREI SENHOR" },
  { number: "188", name: "EU VIVO SEMPRE A CANTAR" },
  { number: "189", name: "ESTA MENSAGEM QUE ESTÁS OUVINDO" },
  { number: "190", name: "BATE NO PEITO" },
  { number: "191", name: "EM TEU SANGUE JESUS" },
  { number: "192", name: "EM ESPÍRITO EM VERDADE" },
  { number: "193", name: "ENCHE-ME ESPÍRITO" },
  { number: "194", name: "ENSINA-ME AMAR" },
  { number: "195", name: "ENTRE NÓS OUTRA VEZ" },
  { number: "196", name: "EXISTE UMA ESTRELA A BRILHAR" },
  { number: "197", name: "FOI TEU SANTO ESPÍRITO" },
  { number: "198", name: "HÁ DE TER UM LUGAR" },
  { number: "199", name: "INCOMPARÁVEL" },
  { number: "200", name: "JERUSALÉM" },
  { number: "201", name: "JESUS NAZARENO PREGADO NA CRUZ" },
  { number: "202", name: "JESUS EM BREVE DO CÉU VIRÁ" },
  { number: "203", name: "JUSTOS E SANTOS" },
  { number: "204", name: "LIVRE SOU" },
  { number: "205", name: "MÃOS ENSANGUENTADAS DE JESUS" },
  { number: "206", name: "MARANATA" },
  { number: "207", name: "MINHA ESPERANÇA FIRME" },
  { number: "208", name: "NA MINHA ANGÚSTIA EU CLAMO" },
  { number: "209", name: "NO MUNDO A GENTE CHORA DE TRISTEZA" },
  { number: "210", name: "NÓS DEVEMOS ESTAR CONFIANTES" },
  { number: "211", name: "HOJE AQUI, MEU JESUS" },
  { number: "212", name: "NOVA FORMA DE VIDA" },
  { number: "213", name: "O ESPÍRITO DE DEUS ESTÁ AQUI" },
  { number: "214", name: "O REI DA GLÓRIA" },
  { number: "215", name: "O SANTO NOME" },
  { number: "216", name: "OS TEUS ANJOS TE EXALTAM" },
  { number: "217", name: "PASSARÃO, PASSAREI" },
  { number: "218", name: "PASSA SENHOR TEU SANGUE SOBRE MIM" },
  { number: "219", name: "PERTO ESTÁ A MÃO DE DEUS" },
  { number: "220", name: "POR AMOR DEUS SE REVELOU" },
  { number: "221", name: "POR ONDE QUER QUE TU FORES" },
  { number: "222", name: "POR QUE É QUE TU NÃO VÊS" },
  { number: "223", name: "PORTAS ABERTAS" },
  { number: "224", name: "QUEM PODERÁ" },
  { number: "225", name: "QUANDO SÓ ME ENCONTRAR" },
  { number: "226", name: "RENDEI GRAÇAS" },
  { number: "227", name: "REUNIMO-NOS AQUI" },
  { number: "228", name: "SALA DO TRONO" },
  { number: "229", name: "SATISFAÇÃO É TER A CRISTO" },
  { number: "230", name: "SE CONFESSARMOS OS NOSSOS PECADOS" },
  { number: "231", name: "SE NA LUTA ESTIVER" },
  { number: "232", name: "SEI QUE EM DEUS EU POSSO CONFIAR" },
  { number: "233", name: "SENTE, DEUS ESTÁ PRESENTE" },
  { number: "234", name: "SONDA-ME" },
  { number: "235", name: "SOU CAMINHANTE AQUI NESTA TERRA" },
  { number: "236", name: "TEMPO DE DEUS" },
  { number: "237", name: "TEUS ALTARES" },
  { number: "238", name: "TODOS ERAM VIS PECADORES" },
  { number: "239", name: "TUDO O QUE SOU" },
  { number: "240", name: "TU ÉS SOBERANO" },
  { number: "241", name: "UMA TORRE EM TEMPO DE GUERRA" },
  { number: "242", name: "UM MILAGRE SENHOR" },
  { number: "243", name: "USA-ME SENHOR" },
  { number: "244", name: "VENCEREI A TENTAÇÃO" },
  { number: "245", name: "O HOMEM DE BRANCO" },
  { number: "246", name: "JESUS GLORIFICADO" },
  { number: "247", name: "ELE É A MINHA FORÇA" },
  { number: "248", name: "PENDURADO NO MADEIRO" },
  { number: "249", name: "FERIDAS" },
  { number: "250", name: "O AMOR DO CALVÁRIO" },
  { number: "251", name: "O AMOR DE DEUS" },
  { number: "252", name: "PELA VIA DOLOROSA" },
  { number: "253", name: "MEU JESUS" },
  { number: "254", name: "LOUVO-TE Ó DEUS" },
  { number: "255", name: "SE A MÃO DE DEUS TOCAR EM MIM" },
  { number: "256", name: "GUIA CRISTO MINHA NAU" },
  { number: "257", name: "ORAÇÃO A JESUS" },
  { number: "258", name: "NUNCA, MEU MESTRE" },
  { number: "259", name: "SANTO ESPÍRITO DE AMOR" },
  { number: "260", name: "A PALAVRA DA VIDA  (FONTE DA CELESTE VIDA)" },
  { number: "261", name: "GUIA, CRISTO, MINHA NAU" },
  { number: "262", name: "ORAÇÃO A JESUS (DIRIJO A TI, JESUS)" },
  { number: "263", name: "QUANDO AO FIM DA JORNADA EU CHEGAR" },
  { number: "264", name: "UM HINO AO SENHOR" },
  { number: "265", name: "AMPARO DIVINO (COM A TUA MÃO)" },
  { number: "266", name: "SÚPLICA" },
  { number: "267", name: "VONTADE SOBERANA (TUA VONTADE)" },
  { number: "268", name: "CONVITE AO TRABALHO (VAMOS NÓS TRABALHAR)" },
  { number: "269", name: "A SANTA PELEJA (ERGA-SE O ESTANDARTE)" },
  { number: "270", name: "UM VASO DE BENÇÃO" },
  { number: "271", name: "VEM A MIM" },
  { number: "272", name: "JESUS NO CÉU ME ENCONTRARÁ" },
  { number: "273", name: "MESA PREPARADA" },
  { number: "274", name: "TOCA EM MIM SENHOR" },
  { number: "275", name: "AO TEU LADO" },
  { number: "276", name: "FALAR COM DEUS" },
  { number: "277", name: "QUANTO TEMPO FAZ" },
  { number: "278", name: "COMECE A GLORIFICAR" },
  { number: "279", name: "CLAMOR DE ANA" },
  { number: "280", name: "ESTOU CONTIGO" },
  { number: "281", name: "SENHOR E PAI (MEU DEUS, MEU PAI)" },
  { number: "282", name: "CARPINTEIRO PREGADOR" },
  { number: "283", name: "DEUS SABE, DEUS OUVE, DEUS VÊ" },
  { number: "284", name: "AJOELHADO" },
  { number: "285", name: "DIGNO É O CORDEIRO" },
  { number: "286", name: "HONRA E GLÓRIA RIQUEZA E PODER," },
  { number: "287", name: "DEUS INDECIFRÁVEL" },
  { number: "288", name: "ADEUS LODEBAR" },
  { number: "289", name: "EXPLOSÃO DE GLÓRIA" },
  { number: "290", name: "OH! COMO É GRANDE E DOCE A PROMESSA" },
  { number: "291", name: "HOMEM DE FÉ" },
  { number: "292", name: "SALMO 105" },
  { number: "293", name: "LEVANTAI OS VOSSOS OLHOS" },
  { number: "294", name: "NÃO DESISTIR" },
  { number: "295", name: "SEMPRE IMAGINEI EM MINHA VIDA" },
  { number: "296", name: "DE SABER" },
  { number: "297", name: "ADORADOR EU SOU" },
  { number: "298", name: "VALENTE" },
  { number: "299", name: "QUANDO EU TENHO SEDE DE TI" },
  { number: "300", name: "DEUS EL SHADAI" },
  { number: "301", name: "NAS MÃOS DE CRISTO" },
  { number: "302", name: "VOLTARÁ" },
  { number: "303", name: "ACENDE A MINHA CANDEIA" },
  { number: "304", name: "CONFIA EM DEUS" },
  { number: "305", name: "QUANDO ME ENCONTROU (FILHO MEU)" },
  { number: "306", name: "EU PRECISO DE TI" },
  { number: "307", name: "ALELUIA! CRISTO É VIVO" },
  { number: "308", name: "ALIANÇA" },
  { number: "309", name: "A PALAVRA DE PODER" },
  { number: "310", name: "BUSCAI A DEUS" },
  { number: "311", name: "BUSQUEM A JESUS" },
  { number: "312", name: "MARAVILHOSO É SERVIR A DEUS" },
  { number: "313", name: "DE HOJE EM DIANTE" },
  { number: "314", name: "DEPENDENTE" },
  { number: "315", name: "DEUS SOMENTE DEUS" },
  { number: "316", name: "DEUS TREMENDO" },
  { number: "317", name: "EIS AQUI MEU CORAÇÃO" },
  { number: "318", name: "EIS QUE PARA MINHA PAZ" },
  { number: "319", name: "ENTREGA" },
  { number: "320", name: "EU TOMO POSSE" },
  { number: "321", name: "EU VEREI (UM MILAGRE EM MINHA VIDA)" },
  { number: "322", name: "FAZ ME LEMBRAR" },
  { number: "323", name: "FIRME ESTAREI" },
  { number: "324", name: "HONRA E GLÓRIA AO REI!" },
  { number: "325", name: "JESUS É A ROCHA" },
  { number: "326", name: "LOUVOR E GLÓRIA" },
  { number: "327", name: "MAIOR É O QUE ESTÁ EM MIM" },
  { number: "328", name: "MEU BARQUINHO" },
  { number: "329", name: "MEU BOM PASTOR" },
  { number: "330", name: "MEU JESUS (MEU SENHOR VOU A TI)" },
  { number: "331", name: "MINH’ALMA CANTARÁ" },
  { number: "332", name: "MOLDA-ME" },
  { number: "333", name: "MUITOS MOTIVOS TENHO" },
  { number: "334", name: "NÃO HÁ O QUE TEMER" },
  { number: "335", name: "NA TUA PRESENÇA" },
  { number: "336", name: "NESTA NOITE EU DECIDI" },
  { number: "337", name: "O DIA DA VITÓRIA" },
  { number: "338", name: "ONDE ESTÁ MINHA ESPERANÇA" },
  { number: "339", name: "OUÇO O SOM" },
  { number: "340", name: "OUVE SENHOR A MINHA PRECE" },
  { number: "341", name: "PAI QUERIDO" },
  { number: "342", name: "PROMESSA DE DEUS" },
  { number: "343", name: "SALMOS DOS SALMOS" },
  { number: "344", name: "SALMO 86" },
  { number: "345", name: "SE DEUS QUISER ME ABENÇOAR" },
  { number: "346", name: "SE EU DISSER" },
  { number: "347", name: "TUDO COOPERA" },
  { number: "348", name: "UMA VEZ MAIS CANTEMOS" },
  { number: "349", name: "VEM Ó PRÓDIGO" },
  { number: "350", name: "VEM, SIM VEM" },
  { number: "351", name: "VIGIAI" },
  { number: "352", name: "VINDE AS ÁGUAS" },
  { number: "353", name: "O ESCUDO" },
  { number: "354", name: "UNÇÃO DO ALTAR" },
  { number: "355", name: "TEU SANTO NOME" },
  { number: "356", name: "ABRIGA-ME" },
  { number: "357", name: "TENTE LEMBRAR" },
  { number: "358", name: "VEM CHEGOU O TEMPO DE ADORAR" },
  { number: "359", name: "FORTES" },
  { number: "360", name: "UM NOVO CORAÇÃO" },
  { number: "361", name: "NINGUÉM SE ESCONDE" },
  { number: "362", name: "CORO" },
  { number: "363", name: "CRISTO, CURA SIM" },
  { number: "364", name: "ALELUIA (A TERRA VAI UM DIA CONTEMPLAR)" },
  { number: "365", name: "NÃO TOQUEIS EM NADA IMPURO" },
  { number: "366", name: "QUÃO GRANDE AMOR (VIGIAI)" },
  { number: "367", name: "EU ME RENDO" },
  { number: "368", name: "DEUS TRÊS VEZES SANTO" },
  { number: "369", name: "VEREI JESUS" },
  { number: "370", name: "QUINHENTOS GRAUS" },
  { number: "371", name: "A IGREJA VEM" },
  { number: "372", name: "AGNUS DEI" },
  { number: "373", name: "AMIGO MAIOR" },
  { number: "374", name: "AMOR VERDADEIRO" },
  { number: "375", name: "AO OLHAR PRA CRUZ" },
  { number: "376", name: "CICATRIZES" },
  { number: "377", name: "COM CRITO É VENCER" },
  { number: "378", name: "COM MUITO LOUVOR" },
  { number: "379", name: "DESCANSAREI" },
  { number: "380", name: "DEUS COMO EU PRECISO DE TI" },
  { number: "381", name: "DEUS DE ABRAÃO" },
  { number: "382", name: "DEUS ME LEVANTA" },
  { number: "383", name: "DIGNO É O SENHOR" },
  { number: "384", name: "ELE NÃO DESISTE DE VOCÊ" },
  { number: "385", name: "ENQUANTO EU VIVER" },
  { number: "386", name: "ESPÍRITO SANTO" },
  { number: "387", name: "EU CUIDO DE TI" },
  { number: "388", name: "EU NAVEGAREI" },
  { number: "389", name: "GETSÊMANI" },
  { number: "390", name: "JÁ SEI SENHOR COMO ENTRAR" },
  { number: "391", name: "JERUSALÉM" },
  { number: "392", name: "JESUS MEU GUIA É" },
  { number: "393", name: "MARANATA" },
  { number: "394", name: "MINHA BENÇÃO" },
  { number: "395", name: "NASCER DE NOVO" },
  { number: "396", name: "NINGUÉM PERDOA ASSIM" },
  { number: "397", name: "O AMOR DE DEUS NÃO MUDA" },
  { number: "398", name: "PRIMEIRA ESSÊNCIA" },
  { number: "399", name: "PROJETO NO DESERTO" },
  { number: "400", name: "QUÃO GRANDE É O MEU DEUS" },
  { number: "401", name: "RESSUSCITA-ME" },
  { number: "402", name: "RESTAURA" },
  { number: "403", name: "SE MEU POVO ORAR" },
  { number: "404", name: "SE VOCÊ CHEGOU ATÉ AQUI" },
  { number: "405", name: "SENHOR DA CRIAÇÃO" },
  { number: "406", name: "TOMA MEU CORAÇÃO" },
  { number: "407", name: "TU SOMENTE ÉS DEUS" },
  { number: "408", name: "TUA GRAÇA ME BASTA" },
  { number: "409", name: "TUDO PRA MIM TU ÉS" },
  { number: "410", name: "HINO DE JERUSALÉM" },
  { number: "411", name: "AH! FILHO MEU PEQUENINO" },
  { number: "412", name: "EIS-ME AQUI (PRA TE SERVIR)" },
  { number: "413", name: "DESCANSAR EM DEUS" },
  { number: "414", name: "EM SILÊNCIO" },
  { number: "415", name: "PROFECIA" },
  { number: "416", name: "PREPARA-TE, Ó ISRAEL" },
  { number: "417", name: "REVELAÇÃO DE JESUS CRISTO" },
  { number: "418", name: "GLÓRIA AO CORDEIRO DE DEUS" },
  { number: "419", name: "O AMOR DE JESUS" },
  { number: "420", name: "VAMOS LOUVAR AO SENHOR" },
  { number: "421", name: "DESFAÇO AS TUAS TRANSGRESSÕES" },
  { number: "422", name: "ACABOU-SE O TEMPO DA DERROTA" },
  { number: "423", name: "JESUS TOMOU O MEU FARDO" },
  { number: "424", name: "DESCEU DA SUA GLÓRIA" },
  { number: "425", name: "UMA CENTELHA SÓ" },
  { number: "426", name: "VOCÊ NÃO ESTÁ SOZINHO" },
  { number: "427", name: "ELE UM DIA ME CHAMOU" },
  { number: "428", name: "ERAM CEM OVELHAS" },
  { number: "429", name: "DEUS CONHECE A TUA VIDA" },
  { number: "430", name: "JESUS CRISTO, REI DOS REIS" },
  { number: "431", name: "BUSCOU-ME COM TERNURA" },
  { number: "432", name: "DEUS DA MINHA SALVAÇÃO" },
  { number: "433", name: "CRISTO É MEU, SIM, CRISTO É MEU" },
  { number: "434", name: "MEU CAMINHO PONHO EM SUAS MÃOS" },
  { number: "435", name: "SOU FELIZ COM JESUS" },
  { number: "436", name: "EU TENHO UM AMIGO" },
  { number: "437", name: "EU SOU FELIZ PORQUE TENHO UM DEUS QUE ME AMA" },
  { number: "438", name: "DIANTE DE TI" },
  { number: "439", name: "NAS ESTRELAS VEJO A SUA MÃO" },
  { number: "440", name: "PEDRA DE ESQUINA" },
  { number: "441", name: "QUANDO ISRAEL SAIU DO EGITO" },
  { number: "442", name: "HOJE SEI, SENHOR" },
  { number: "443", name: "CADA DIA QUE EU VEJO O SOL" },
  { number: "444", name: "OUVE, Ó DEUS" },
  { number: "445", name: "DELEITA-TE TAMBÉM NO SENHOR" },
  { number: "446", name: "ESPEREI CONFIANTEMENTE NO SENHOR" },
  { number: "447", name: "SENHOR, ME ENSINA" },
  { number: "448", name: "DEUS É O NOSSO AUXÍLIO" },
  { number: "449", name: "CANTA ALEGREMENTE, Ó FILHA DE SIÃO" },
  { number: "450", name: "UMA VOZ ME DISSE LÁ DO CÉU" },
  { number: "451", name: "QUE DIA FELIZ" },
  { number: "452", name: "SENHOR, EU QUERO DEPOSITAR" },
  { number: "453", name: "A TEUS PÉS, JESUS" },
  { number: "454", name: "JESUS, EU TE AMO E MUITO" },
  { number: "455", name: "EXALTAI AO SENHOR" },
  { number: "456", name: "EU VENHO DIZER" },
  { number: "457", name: "LOUVADO SEJA O NOME DO SENHOR" },
  { number: "458", name: "EU VENHO A TI, SENHOR" },
  { number: "459", name: "BOM É LOUVAR AO SENHOR" },
  { number: "460", name: "BENDIZE, Ó MINH’ALMA AO SENHOR" },
  { number: "461", name: "LOUVAI AO SENHOR PORQUE ELE É BOM" },
  { number: "462", name: "NÃO A NÓS, SENHOR" },
  { number: "463", name: "O SENHOR REINA" },
  { number: "464", name: "NO PRINCÍPIO ERA O VERBO" },
  { number: "465", name: "QUÃO DOCE E MEIGO É OUVIR" },
  { number: "466", name: "SENHOR, TU ME SONDASTE E ME CONHECES" },
  { number: "467", name: "QUANDO OS CÉUS ESTOU A CONTEMPLAR" },
  { number: "468", name: "ONDE ESTÁ JESUS (OVELHA PERDIDA)" },
  { number: "469", name: "HÁ UMA PÁTRIA ETERNAL" },
  { number: "470", name: "TRONO BRANCO" },
  { number: "471", name: "SALMO 5" },
  { number: "472", name: "DAS PROFUNDEZAS (SALMO 130)" },
  { number: "473", name: "JESUS, ALEGRIA DOS HOMENS" },
  { number: "474", name: "QUAL SUSPIRA A CORÇA INQUIETA" },
  { number: "475", name: "PRECIOSA GRAÇA (AMAZING GRACE)" },
  { number: "476", name: "DEIXA MEU POVO IR (VAI MOISÉS)" },
  { number: "477", name: "SONHEI COM JESUS ESTA NOITE" },
  { number: "478", name: "TUA ALMA ESTÁ FERIDA, MAGOADO O CORAÇÃO" },
  { number: "479", name: "VIVEREMOS PELA FÉ" },
  { number: "480", name: "IGREJA PODEROSA" },
  { number: "481", name: "O CAMINHO DE SIÃO" },
  { number: "482", name: "CIDADE ETERNAL" },
  { number: "483", name: "PILARES DE UM CRISTÃO" },
  { number: "484", name: "IMUTÁVEL DEUS" },
  { number: "485", name: "NÃO HÁ O QUE TEMER (SEI QUE DEUS É POR MIM)" },
  { number: "486", name: "CANTA IGREJA, IGREJA FIEL!" },
  { number: "487", name: "PELA FÉ AVISTAMOS ALÉM (NO DOCE PORVIR)" },
  { number: "488", name: "O FIM VEM!" },
  { number: "489", name: "AOS PÉS DE JESUS" },
  { number: "490", name: "NÃO SE TURBE O VOSSO CORAÇÃO" },
  { number: "491", name: "NA ESTRADA DA VIDA (JESUS COMPANHEIRO)" },
  { number: "492", name: "QUANDO LÁ DO CÉU DESCENDO" },
  { number: "493", name: "PÕE-ME COMO SELO" },
  { number: "494", name: "OUVI NO CÉU (BODAS DO CORDEIRO)" },
  { number: "495", name: "O MEU VIVER É CRISTO" },
  { number: "496", name: "EIS-ME, Ó SALVADOR, AQUI" },
  { number: "497", name: "FALA SENHOR QUE TEU SERVO OUVE" },
  { number: "498", name: "HONRA E GLÓRIA AO CORDEIRO" },
  { number: "499", name: "JARDIM DE ORAÇÃO" },
  { number: "500", name: "PELAS MARAVILHAS" },
  { number: "501", name: "TODA TERRA EXALTAI" },
  { number: "502", name: "BARNABÉ, HOMEM DE DEUS" },
  { number: "503", name: "HÁ ESPERANÇA" },
  { number: "504", name: "AINDA HÁ TEMPO" },
  { number: "505", name: "VARÃO DE GUERRA É O SENHOR" },
  { number: "506", name: "CANTE ALELUIA" },
  { number: "507", name: "BASTA-NOS A TUA GRAÇA" },
  { number: "508", name: "ORAÇÃO DO PASTOR" },
  { number: "509", name: "CORO" },
  { number: "510", name: "SHEKINAH" },
  { number: "511", name: "TU CONSERVARÁS EM PAZ" },
  { number: "512", name: "JESUS, O MISTÉRIO REVELADO" },
  { number: "513", name: "EM CAMINHOS DE DOR" },
  { number: "514", name: "FORTE DEUS" },
  { number: "515", name: "SALMO 23 (Ó, SENHOR,TU ÉS O MEU PASTOR)" },
  { number: "516", name: "BASTA-NOS TUA GRAÇA, SENHOR" },
  { number: "517", name: "UMA VOZ MANSA E DELICADA" },
  { number: "518", name: "CELEBRAI" },
  { number: "519", name: "Ó VENHA!" },
  { number: "520", name: "TORRE FORTE" },
  { number: "521", name: "SITUAÇÕES" },
  { number: "522", name: "CALMO, SERENO E TRANQUILO" },
  { number: "523", name: "O AMANHÃ NÃO SEI SE VEM" },
  { number: "524", name: "OH! QUE PAZ JESUS ME DÁ" },
  { number: "525", name: "TUDO ESTÁ PRONTO (A CEIA)" },
  { number: "526", name: "EU SEI QUE SOU FRACO (CRISTO É FORTE)" },
  { number: "527", name: "OLHAR UNICAMENTE A JESUS" },
  { number: "528", name: "CREIO NESTE DEUS" },
  { number: "529", name: "VEM A MIM, SE CANSADO E FERIDO ESTÁS" },
  { number: "530", name: "EM OBEDIÊNCIA, SERVI AO SENHOR" },
  { number: "531", name: "ELE ESTÁ AGINDO" },
  { number: "532", name: "É LINDO, É LINDO, SIM" },
  { number: "533", name: "EU TENHO UM AMIGO" },
  { number: "534", name: "JARDIM DE DEUS" },
  { number: "535", name: "JUNTO A TI" },
  { number: "536", name: "LINDA CIDADE" },
  { number: "537", name: "LUGAR DA ORAÇÃO" },
  { number: "538", name: "O JORDÃO EU NÃO PASSAREI SÓ" },
  { number: "539", name: "SÚPLICA" },
  { number: "540", name: "ALELUIA, AMÉM" },
  { number: "541", name: "AINDA QUE A FIGUEIRA NÃO FLORESÇA" },
  { number: "542", name: "PELA FÉ QUE UMA VEZ ME FOI DADA" },
  { number: "543", name: "NO CÉU NÃO ENTRA PECADO" },
  { number: "544", name: "RIQUEZAS MIL" },
  { number: "545", name: "SENHOR, VEM FICAR COMIGO" },
  { number: "546", name: "JESUS IRÁ VOLTAR!" },
  { number: "547", name: "NÃO HÁ DEUS COMO NOSSO DEUS" },
  { number: "548", name: "QUAL FOI O PREÇO" },
  { number: "549", name: "OS OLHOS DA FÉ" },
  { number: "550", name: "VIDA EM ABUNDÂNCIA" },
  { number: "551", name: "TERÁS VIDA EM OLHAR PRA JESUS" },
  { number: "552", name: "CRISTO VALERÁ" },
  { number: "553", name: "PÉS DIVINOS" },
  { number: "554", name: "E VEIO A MIM" },
  { number: "555", name: "PERANTE A TUA GRANDEZA" },
  { number: "556", name: "ROSA VERMELHA" },
  { number: "557", name: "QUEM SOU EU, SENHOR (VASO DE ALABASTRO)" },
  { number: "558", name: "SE TUA ALMA ALEGRE ESTÁ" },
  { number: "559", name: "A ORAÇÃO DA TUA IGREJA" },
  { number: "560", name: "EM MEIO À MULTIDÃO" },
  { number: "561", name: "O AMIGO INCOMPARÁVEL" },
  { number: "562", name: "Ó CRISTO, PÃO DA VIDA" },
  { number: "563", name: "INDA É LONGE CANAÃ" },
  { number: "564", name: "SOCORRE-ME, SENHOR" },
  { number: "565", name: "DEUS DA PROVISÃO" },
  { number: "566", name: "VEM, MEU FILHO (ALGEMAS)" },
  { number: "567", name: "MARANATA (EM BREVE, MUI BREVE)" },
  { number: "568", name: "TEU AMOR" },
  { number: "569", name: "MARAVILHOSO" },
  { number: "570", name: "CANTARES 2" },
  { number: "571", name: "SOBE AQUI" },
  { number: "572", name: "GADARENO" },
  { number: "573", name: "ARREPENDEI-VOS" },
  { number: "574", name: "EU CLAMO PELO SANGUE DE JESUS" },
  { number: "575", name: "FAZ-ME LEMBRAR" },
  { number: "576", name: "ALELUIA" },
  { number: "577", name: "EIS O ALTAR DO HOLOCAUSTO" },
  { number: "578", name: "ELEVO A MINHA VOZ" },
  { number: "579", name: "QUE VISTA ALI NO MONTE" },
  { number: "580", name: "O REI VEM!" },
  { number: "581", name: "OBRA SANTA" },
  { number: "582", name: "BÊNÇÃO AARÔNICA" },
  { number: "583", name: "BUSCAR-TE-EI, SENHOR!" },
  { number: "584", name: "CRISTO, O CORDEIRO" },
  { number: "585", name: "PORQUE DEUS AMA" },
  { number: "586", name: "TABERNÁCULO" },
  { number: "587", name: "CRER E OBSERVAR" },
  { number: "588", name: "OBEDECER" },
  { number: "589", name: "ALTO PREÇO" },
  { number: "590", name: "AVULSO_DESCONHECIDO_591" }
];